### ISSUE TITLE
Add default tasks to new team

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6719] opened 2022-06-10 14:39 UTC
When a user creates a new team, the /team view should have two tasks assigned to that user
1. "Congratulations to your new team, you can now start inviting your team mates[link to open invite modal]"
2. "Start your first meeting in your new team [link to meeting lobby]"

**Events to measure**
- Clicks on the cards
- Cards moved to done
- Cards set to archived

**Comment by JimmyLv** [comment] 2022-06-15 14:49
Hi @acressall I would like to confirm the details, which here refers to:

1. does this logic trigger whenever a user creates a new team? and in these each new team, when a user creates a new meeting, two tasks are created?
2. in the first text, is there a space or comma before `[link to open invite modal]` that appears like the one in my screenshot? It feels a bit strange, maybe I misunderstood it 🤣
3. about `[link to meeting lobby]`, since the user in #1 has already created a new meeting, does this mean jumping directly to the meeting page, e.g. https://action.parabol.co/meet/eb0aFGeaSQ?


<img width="1394" alt="Google Chrome-Team Dashboard  Jimmy Test Team-003315-20220615" src="https://user-images.githubusercontent.com/4997466/173856326-5a512bdc-e924-43e9-9984-cf5bc1e59dce.png">

**Comment by acressall** [comment] 2022-06-15 22:53
> does this logic trigger whenever a user creates a new team? and in these each new team, when a user creates a new meeting, two tasks are created?

Yes, these are created for each team, but _before_ their first meeting. Right now, after you create a team you are taken to the team dashboard, but it's empty. So we're adding these two tasks so you know what to do next.

> in the first text, is there a space or comma before [link to open invite modal]
the link should actually be in the text. Here's what it would look like:
**Congratulations on your new team! You can now start [inviting your teammates](google.com)**

> about [link to meeting lobby], since the user in #1 has already created a new meeting, does this mean jumping directly to the meeting page
I don't think they'll have started a meeting first, but once they do start one it might become confusing. Let's change it to this:
**[Start a meeting](#) with your team**

**Comment by JimmyLv** [comment] 2022-06-16 06:51
Thanks for the reply, make sense! ✌️

The first sentence in the issue description is `When a user creates a new meeting`, so I got confused, and it should be `When a user creates a new team` right? 🤣

```diff
-      When a user creates a new meeting
+     When a user creates a new team
```

**Comment by JimmyLv** [comment] 2022-06-16 07:54
> [Start a meeting](https://action.parabol.co/new-meeting/dFmFaUUzfi?source=BottomFAB) with your team
The user will be redirected to the page where the meeting was created, right? So at this point, I think we should mark the URL with source, e.g. `/new-meeting/${teamId}?source=TeamTask`. and the other two entry points that are already there:

- `/new-meeting/${teamId}?source=TopBar`
- `/new-meeting/${teamId}?source=BottomFAB`

![Google Chrome-Team Dashboard  Product Squad 2-003350-20220616](https://user-images.githubusercontent.com/4997466/174020578-7ddf201f-85bd-47bd-98bc-6a1165c8bcb2.png)

**Comment by Dschoordsch** [comment] 2022-06-17 09:27
Adding the `?source=TeamTask` parameter seems fine for me right now.

We should add the tasks also to the initial team, but maybe put some in future. We should also revisit the copy of "Congratulations on your new team..." and "This is task card..." for this scenario. @acressall what do you think?

**Comment by acressall** [comment] 2022-06-20 13:58
I think we try keeping them with the same copy for now, but agree that they can go in the future column

**Comment by acressall** [comment] 2022-06-22 19:42
Noted in [this doc](https://www.notion.so/parabol/Onboarding-Create-an-onboarding-team-with-onboarding-tasks-c6fa6ab6a1924757b5f11b3853158418), but stating here as well -- let's include these new tasks in the onboarding team as well!

**Comment by mattkrick** [comment] 2022-06-24 21:18
We used to have these tasks! We got rid of them because we got SO MUCH feedback about how users hated that the first thing they had to do was delete them-- so we compromised & left 1 😅 . 

For onboarding, we replaced them with Suggested Actions, which live at the top of your timeline. They include:
- Try the demo
- Invite your team
- Try a Retro
- Try a Check-in
- Create a new team

Task cards aren't ideal for this work because there's no easy way to make links that don't trigger a page refresh (or opening a new tab). This leads to a pretty poor UX & is something we'd like to avoid.

@ackernaut could you work with Squad 2 to come up with a good design on how we can take what we've learned in the past & build something that doesn't replicate what we have on our timeline?

**Comment by JimmyLv** [comment] 2022-07-11 02:48
> Can we just trigger the invite modal opening for the "add your teammates" task?
@acressall From my understanding, technically we can't. Because the task card can only contain 🔗 links, thus indirectly triggering the invite modal with a refresh or new tab, and cannot directly trigger other UI behaviors.

@mattkrick For Suggested Actions, honestly I didn't realize this feature until after you mentioned it. 😁
Timeline's Suggested Actions are global, and if there are multiple new teams, it seems no way to have guided Suggested Actions for a particular team? 
I agree that we need a new design, that makes it easy to guide the user to the desired behavior on the /team page, and I don't have a better idea at the moment.

![Google Chrome-My Timeline  Parabol-003500-20220711](https://user-images.githubusercontent.com/4997466/178178822-f46aeeb0-f517-472b-b0d1-81a60ddb80ce.gif)

**Comment by mattkrick** [comment] 2022-07-13 19:06
> Timeline's Suggested Actions are global, and if there are multiple new teams, it seems no way to have guided Suggested Actions for a particular team?

we do some magic here & just make the action apply to the first team you created

> I agree that we need a new design, that makes it easy to guide the user to the desired behavior on the /team page, and I don't have a better idea at the moment.

it's a hard problem to solve for! we don't want new folks to see us as a task manager, so if they see a kanban it's probably not a great first impression (which is why we moved the home page to the timeline, and then later to meetings). Ultimately, we'll want the team dashboard to just have team settings & history-- do away with the kanban on that view entirely. I'm not sure what the right answer. We could spruce up the suggested actions, improve the empty state of the /meetings page, or if there are other issues that have more certainty, we can focus on those & chances are a better idea will come up later

**Comment by JimmyLv** [comment] 2022-07-14 16:49
> Ultimately, do away with the kanban on that view entirely.

good to know that eventually we will remove the task kanban board from the team dashboard! (btw, will we continue to strengthen the task manager's capabilities in other places?)

Well, because we can't avoid this problem of directly triggering the invite modal without a refresh or new tab.
I suggest that we could only add one task of the ACs?
- `Start your first meeting in your new team [link to meeting lobby]`

If it is doable, later I will modify the code of PR #6773.

**Comment by JimmyLv** [comment] 2022-07-25 04:29
In the long term, we have not yet determined the pattern of the task manager on each `/team` page.
Then in the context of the problem this issue is trying to solve, I still suggest we continue with the experiment (at least 1 task):
1. currently when a new TEAM is created, the whole panel is empty. It would be much better if we add one task?
2. we want to collect data first, at least to see if the task can be used as a guide for users to open more meetings?
3. and then we may come back to optimize things like "auto-archived after the user clicks on task"

![Google Chrome-Team Dashboard  Yet Another Team-003705-20220725](https://user-images.githubusercontent.com/4997466/180698585-e2496d8e-a1c1-47a3-8eda-c47ce0cbbe3c.png)

Just like the modified PR https://github.com/ParabolInc/parabol/pull/6773, I've only added 1 task for the new team, to _[Start a meeting]() with your team_

https://www.loom.com/share/b87f9c82662b4526881ebe4f1e2aaf63

**Comment by Dschoordsch** [comment] 2022-07-26 14:56
@acressall can we just do one task and add a checklist with links? Something along the lines of
* Invite members
* Create new meeting
* Archive this task

**Comment by acressall** [comment] 2022-07-29 14:16
@JimmyLv I discussed with the marketing team and we decided to stick with _one_ action to keep it focused. Here's the [slack conversation.](https://parabol.slack.com/archives/C2790TSTT/p1658858014695239)

Copy:
`🎉 Welcome to your new team! You can now start inviting your teammates`

"Inviting your teammates" should link to the invite modal.

Testing:

- Let's add an event to the task link so we know when this link specifically is clicked
- Can we add an event for copying the invite link?
- We'll create an Amplitude funnel for:

1. Creates new team
2. Clicks on task link
3. Copies the invite link OR sends invite email

[Amplitude WIP](https://analytics.amplitude.com/parabol/chart/1mnkdwz)

**Comment by mattkrick** [comment] 2022-08-01 17:42
I'm all for experimentation & if you want to move forward with it, that's OK.
However, I think this is a bad idea.

Here's why:
- Creating an in-app link vs. a link that opens a new tab is going to be difficult. A link that opens a 2nd instance of our app in a new tab isn't a UX we want to use.
- Creating a seed card may be useful for the first time they create a new team. But their 2nd-100th use is now belabored because they have to delete the seed card.

CC @ackernaut for design help

**Comment by acressall** [comment] 2022-08-02 18:50
Thanks for the feedback!
Here's how I'd like to move forward:

- We implement this (knowingly imperfect) first step to giving the teams view more context
- We check if people do anything with the card within 1 month. @JimmyLv let's make sure to have tracking on the link. We'll check the amount of clicks relative to the amount of new teams that are created after this is implemented. I'd also like to find away to view the engagement of users who sign up via this invite (@tianrunhe is it possible to view/segment users who have signed up from these invites?)
- We'll monitor for user feedback related to the automatic task
- After the 1 mo we review and decide whether or not to keep and / or improve this 

We'll track feedback and stats in this Notion card: https://www.notion.so/parabol/Squad-2-Notes-515904adde5441febd81750e4c7a1e65?p=fb3a6f024f1c40019ddc70133b6b12f1&pm=s

Extra context: I'm about to take a step back and look at onboarding as a whole. This experiment will give me extra info for how to approach the "create a new team" flow

**Comment by ackernaut** [comment] 2022-08-04 23:00
Sorry I’m late to the party on this one! I sense there’s been a little back and forth on trying to move this forward. In the future, move on to the PM if I don’t respond in time and something seems stuck on design.

I created an account today with the current flow:
- I landed on the Meetings view with a card for a Retro Demo and another for starting a Sprint Poker
- My default team has 2 tasks: 1 about the general task card and another with a link to Settings & Integrations; the link opens to a new tab
- When I create an additional team, it’s just empty

I tried this locally.
- I created a new local account
- There are 3 task cards on the initial team: 1) this is a task 2) settings & integrations 3) invite your team
- When creating an additional team that team only gets the task card to invite your team
- The links open to a new tab

What are we designing for?
- Are we designing for first-time users so that they can learn how to set up?
- Is is necessary to have those cards later on when they create additional teams, assuming they’ve learned the motions? I’m not sure folks need direction to invite their team at that point, either.
- Has there been much feedback that folks don’t know how to invite to teams? It seems to me that this doesn’t come up often, but could be wrong
- It seems to me there may be more feedback about not knowing how to set up integrations?
- I suppose we’re looking for a quick win that is aligned with the squad mission of initial friction and churn?

Feedback
- I think using the cards to solve for this is clever, but doesn’t solve root causes
- We’ve already had some learning here in the past and I’m not sure much has changed
- I’m not sure it’s apparent anywhere that we’ve wanted to deprecate the team kanban view. It makes me wonder how much effort to put here. I’m not sure when a MVP team view will be on strategy; maybe it’s off-strategy work?
- I don’t think we should have 3 cards. I don’t like having the chore of getting rid of default content, apps, etc. when I have something new. I’m not sure I need the card when creating new teams. I think I’d prefer the empty state if drinking our own champagne.
- I think an empty state for new users may be more appropriate in a team view; I think an empty state for established users may be better when creating teams later. I would rather see that effort applied to a new team view
- If folks are having problems knowing to set up integrations, I admit the quick win of the card. However, how can we improve the actual IA and pattern of setting up integrations? Has any work been scoped there? That work is probably more involved but more viable for us in the long run. It probably overlaps with a new team view

Moving forward
- This is @acressall ’s design work; she has recommendations on how to move forward, my feedback there:
  - These cards ideally shouldn’t open in a new tab. The links don’t support direct interactions. Any way to make this a good UX without links?
  - I wish we could edit away some cards. Now we will have 3 for initial team + 1 for every new team. Our earlier trade-off was 1 for the first team. We are adding more. How do we know when to stop?
  - I can see how it would be nice to know if these are having a positive or negative effect. I suspect adding tracking on these card links is even more effort creep, making this more of a sunk cost.
- Some folks are willing to see more exploration here (I see Jimmy and Matt’s comments). I’m not sure what to explore, but making space for the onboarding exploration you want to do may be a step. Another step might be a new team view, if that would reduce friction to getting a team set up. Another may be to think about how folks learn about integrations. I think any sunk cost here (design, PR, feedback efforts) is fine if it yields learning about direction, gives us an opportunity to adapt, and puts us in a better position. **_In my opinion_** I think we should be more comfortable with that kind of opportunity and not see this as wasted effort

**Comment by acressall** [comment] 2022-08-17 01:54
Thanks for the detailed feedback @ackernaut!
I'm still a little unclear on how to move forward. Are there firm objections? Is there uncertainty (if so, let's arrange a sync chat)?

**Comment by Dschoordsch** [comment] 2022-08-17 10:23
We observed users were lost at the beginning and figured adding a task with next steps might help them.

So how many teams are actually created? 76% of all teams are onboarding teams [^1].
How many users create a new team after signing up? <2% [^2].

Given these numbers it's not worth pursuing/discussing this any further.

[^1]: https://colab.research.google.com/drive/1GfPxjEQx60pQTm0YKXsIhVWTSrsy6cSS#scrollTo=QL_AKYHkIVNh
[^2]: https://analytics.amplitude.com/parabol/chart/9xi0zux?source=team%20space%20item%20table

**Closed by Dschoordsch** 2022-08-17 10:23 UTC
Labels: enhancement, design, Story Points: 8, Squad: 2

**Comment by JimmyLv** [comment] 2022-08-17 10:58
Just want to clarify, as well as add what I have found:
1. invited members barely create new teams, 0.3%; for self-registered team members, the figure is 3.99% https://analytics.amplitude.com/parabol/chart/9xi0zux/edit/94u41mk with `invited=False`

2. 76% of teams are using only onboarding teams, is it because the organization not big enough to have a need for them? Thus, there is no need to create multiple teams.
By the way, how does this overlap with turning on Pro or Enterprise accounts?
