### ISSUE TITLE
Export tasks on dashboard to csv

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4529] opened 2021-01-14 23:31 UTC
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/10398101) 🔒  has requested a feature that would allow the task cards on a team dashboard to be exported to a csv

**Comment by shawneeatparabol** [comment] 2021-01-15 23:11
This is part of Issue [#4379: Ability to manually import from CSV to Parabol](https://github.com/ParabolInc/parabol/issues/4379)

**Comment by shawneeatparabol** [comment] 2021-01-15 23:11
Duplicate of #4379

**Comment by jordanh** [comment] 2021-01-26 19:25
Closing duplicate

**Closed by jordanh** 2021-01-26 19:25 UTC
Labels: enhancement, user request
