### ISSUE TITLE
Poker: Estimate: Links in header cards don't open in new tab 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6351] opened 2022-04-05 20:37 UTC
Links in an issue should open in a new tab when they're clicked.
To do this, I think we'll have to intercept the HTML coming in from github/jira & attach a `_blank` to the anchor tag, but that's just a suggestion. How you decide to do it is up to you.

AC
- [ ] when I click a link in an Estimate Header card for a github or jira issue, it opens in a new tab

Estimate: 4 hours

**Comment by Dschoordsch** [comment] 2022-04-06 08:09
Duplicate of #6194

**Closed by Dschoordsch** 2022-04-06 08:09 UTC
Labels: enhancement
