### ISSUE TITLE
Activity Library: fatal error when trying to view tempalte

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#8963] opened 2023-10-12 18:46 UTC
## Issue - Bug

- **How serious is the bug?** P2
- **OS:** macOS
- **Browser:** Chrome

See Loom: https://www.loom.com/spaces/All-Parabol-1227113/folders/Product-e023e17d90db483bba05238d0c0fde7c

Steps:
- Navigate to Parabol's "Company" team
- Search for "New" to filter templates
- Choose one of the `*New Template` templates, if you do not receive an error try another template until you receive the error

### Acceptance Criteria (optional)
Users can:
   - Select template without fatal error occurring

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment] 2023-10-12 18:51
Related: https://github.com/ParabolInc/parabol/issues/8964

**Comment by mwermuth** [comment] 2023-10-18 10:31
Hey @BartoszJarocki I know you were looking into some bugs in the Activity Library. Would you mind taking a look at this one if you get a chance?

**Comment by BartoszJarocki** [comment] 2023-11-03 13:20
@mwermuth @jordanh I can't reproduce this. @jordanh do you mind double checking if bug still exists on your end?

**Comment by mwermuth** [comment] 2023-12-01 12:38
I wasn't able to replicate this. Closing it for now.

**Closed by mwermuth** 2023-12-01 12:38 UTC
Labels: bug, p2, Squad - Excite & Expand
