### ISSUE TITLE
Ready progress and votes count calculated by present team members

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#6002] opened 2022-02-04 18:27 UTC
## Issue - Enhancement

Today the progress bar for the ready button and votes remaining are calculated by number of meeting members. This means that if a team member participated in an early phase but are absent while the facilitator is advancing, he/she is still counted against the ready progress or votes remaining.

Instead of blindly using all meeting members when calculating those two metrics, we should filter by `isConnected`

### Acceptance Criteria (optional)
- [ ] In retro meeting and poker meeting, the ready button progress bar is calculated by present meeting members
- [ ] In retro meeting, the number of votes is calculated by present meeting members
- [ ] In poker meeting, the voting consensus button is calculated by present meeting members

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment] 2022-05-25 19:38
Duplicate of #6210, closing this one

**Closed by jordanh** 2022-05-25 19:38 UTC
Labels: enhancement
