### ISSUE TITLE
Inability to hold simultaneous retrospectives

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#3856] opened 2020-05-18 23:35 UTC
## Issue - Bug

a team leader (https://app.hubspot.com/contacts/3888472/contact/8599251) said his team led a retrospective without him, while he was simultaneously attending another retrospective led by someone else. When the team he was a leader on ended their retro, the meeting he was in as a member was also cut off.

Acceptance Criteria
- Attempted to reproduce and triage by running two simultaneous meetings with a friend

EE: 1 hour

**Comment by jordanh** [comment] 2020-05-26 17:12
@shawneeatparabol, we tried to reproduce this as a team today and were unable to reproduce it. Steps taken:

1. M & T started a retro and was in Icebreaker when
2. J started his own meeting on a separate team
3. J proceeded to Group phase
4. M & T ended their meeting
5. We observed that J's meeting did not end

Closing for now, will reopen if this occurs again or if we get more information.

**Closed** 2020-05-26 17:30 UTC
Labels: bug
