### ISSUE TITLE
Poker meeting crashing

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6015] opened 2022-02-08 17:50 UTC
## Issue - Bug

One of our [poker meeting](https://action.parabol.co/meet/aGjmYpJBIs) isn't loading. 
Investigate what's the root cause and figure out the next steps.

related slack thread: https://parabol.slack.com/archives/C836NA350/p1644328590076379

### Acceptance Criteria (optional)
- [ ] root cause identified 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tianrunhe** [comment] 2022-02-08 18:22
APM indicated that the TaskIntegration resolver took too long to execute:

![](https://user-images.githubusercontent.com/1879975/153051386-0c8d59a2-49e4-4afe-8481-71f9aad8ea1d.png)

**Comment by mattkrick** [comment] 2022-02-08 21:23
cloned prod DB to local & will try to debug further

**Comment by igorlesnenko** [comment] 2022-02-09 09:21
Minimum query to reproduce the issue. Takes more than 20 seconds for me

```
query MeetingSelectorQuery {
  viewer {
    isConnected
    meeting(meetingId: "aGjmYpJBIs") {
      __typename
      __isNewMeeting: __typename
      ...PokerMeeting_meeting
      meetingType
      id
    }
    id
  }
}


fragment PokerMeeting_meeting on PokerMeeting {
	...PokerMeetingSidebar_meeting
  id
  init: id
  phases {
    __typename
    phaseType
    stages {
      __typename
      id
    }
    id
  }
}

fragment PokerMeetingSidebar_meeting on PokerMeeting {
	...PokerSidebarPhaseListItemChildren_meeting
  settings {
    phaseTypes
    id
  }
  id
  endedAt
  facilitatorUserId
  facilitatorStageId
  phases {
    __typename
    phaseType
    stages {
      __typename
      id
      isComplete
      isNavigable
      isNavigableByFacilitator
      ... on EstimateStage {
        taskId
      }
    }
    id
  }
}

fragment PokerSidebarPhaseListItemChildren_meeting on PokerMeeting {

	  ...PokerSidebarEstimateSection_meeting
  phases {
    __typename
    phaseType
    stages {
      __typename
      isComplete
      id
    }
    id
  }
}


fragment PokerSidebarEstimateSection_meeting on PokerMeeting {
  id
  endedAt
  facilitatorStageId
  phases {
    __typename
    ...useMakeStageSummaries_phase
    ... on EstimatePhase {
      stages {
        scores {
          userId
          id
        }
        id
      }
    }
    phaseType
    stages {
      __typename
      id
    }
    id
  }
}

fragment useMakeStageSummaries_phase on EstimatePhase {
  phaseType
  stages {
    id
    finalScore
    isComplete
    isNavigable
    sortOrder
    taskId
    task {
      title
      integration {
        __typename
 
        ... on _xGitHubIssue {
          __typename
          title
          number
        }
        id
      }
      id
    }
  }
}
```

The exact slow place is

```
task {
      title
      integration {
```

**Comment by igorlesnenko** [comment] 2022-02-09 09:38
The issue is here:
https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/types/Task.ts#L152

it called a lot of times and it is slow

**Comment by mattkrick** [comment] 2022-02-09 20:26
that is wonderful! i guess 6 years of tasks for our product team means too many tasks to filter efficiently 😉 
I'll update #6023 -- looks like we're running that query in O(n) when it should be O(1)

**Comment by mattkrick** [comment] 2022-02-12 03:31
closing in favor of #6024

**Closed by mattkrick** 2022-02-12 03:31 UTC
Labels: bug, p1, Story Points: 1
