### ISSUE TITLE
Implement Estimate Phase Mocks v1

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4186] opened 2020-09-22 18:33 UTC
AC
- [ ] In a sprint poker meeting, can click "next" from the SCOPE phase & advance to the estimate phase
- [ ] If there are no estimate stages, a screen tells them that there are no items to estimate & it provides a link to the SCOPE phase (build this, but no need to use the logic to point here, just point to the mock by default)
- [ ] The header component has the Estmate title & subtitle
- [ ] A mock wide Task card exists as seen here: https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2689%3A118425
- [ ] 2 mock Swipeable columns exists for 2 mock dimensions
(https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2689%3A118425)

Estimate: 30 hours

**Comment by jordanh** [comment] 2020-09-29 17:28
Duplicate of #4185, closing this one

**Closed by jordanh** 2020-09-29 17:28 UTC
