### ISSUE TITLE
Invites are broken - Cannot destructure property 'isConnected' of 'n' as it is null.

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5282] opened 2021-08-19 14:28 UTC
## Issue - Bug

Currently, when user clicks the invite link (no matter if sent via email, or just copied) the following error happens:
https://sentry.io/organizations/parabol/issues/2514125484/?query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved 

server error: 
https://sentry.io/organizations/parabol/issues/2529187067/events/f504e23941dd44b9b81818710a44468b/?environment=server&project=107196 

Reproduction steps
1. Copy invite link
2. Open incognito, login/sign up 
3. Error happens

Refreshing the page allows joining the meeting without any issues. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment] 2021-08-19 17:23
root cause was logrocket :exploding_head:. We probably don't do a graceful fallback somewhere, but as a quick fix we just removed it.

**Comment by mattkrick** [comment] 2021-08-19 18:58
still a problem. weird how disabling logrocket made it go away in dev :thinking:

**Comment by mattkrick** [comment] 2021-08-19 20:31
upgrading to relay today & tomorrow, will retest after upgrade is complete. i think this is related to relay holding onto a stale version where viewer is null so it's not fetching fresh from the network.

**Comment by tiffanyhan** [comment] 2021-08-23 23:03
I think this is probably the same issue, but it looks like there was a network issue for a moment with resolving client source maps so not totally sure.

Sentry issue: [ACTION-PRODUCTION-94V](https://sentry.io/organizations/parabol/issues/2588822241/?referrer=github_plugin)

**Comment by mattkrick** [comment] 2021-08-24 18:08
reproduced locally in #5294. 
fixed (locally) in #5310

**Closed by mattkrick** 2021-08-24 18:08 UTC
Labels: bug
