### ISSUE TITLE
Reflection cards 'disappear' when advancing phases

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4343] opened 2020-11-13 22:44 UTC
## Issue - Bug

From the 🔐 [client](https://app.hubspot.com/contacts/3888472/contact/17209851/):
"I am not sure of exact steps to reproduce this, but every now and then I will have a team member who's cards will get lost when we go from the "Reflect" to "Group" page. Any idea why this might be happening, and how we can avoid it in the future?"

Have asked for further information but logging now in case it is reported by any other users.

**Comment by jordanh** [comment] 2020-11-17 19:09
This might be caused by a connectivity issue on the client where a card is created, but the client misses the card created event. When they navigate to the group phase, any missed cards will not appear. Refreshing would work around this.

To "robustify" this, we could assert the Group phase always begin with a fresh query of all cards from the server.

**Comment by jordanh** [comment] 2020-11-17 19:10
AC
- [ ] request full query of cards at start of Group phase

EE
8 hours

**Comment by jordanh** [comment] 2020-12-08 19:05
Closing in favor of #4410

**Closed by jordanh** 2020-12-08 19:05 UTC
Labels: bug
