### ISSUE TITLE
Standups: Pay off technical debt

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6588] opened 2022-05-19 08:15 UTC
Collecting PR comments which I think should be fixed long term but were omitted initially to move faster. Should be tackled once we know what we're doing with standups.

> +1 would be nice to use the same structure `{id, userId}` in Postgres so we could get away with just casting.

_Originally posted by @Dschoordsch in https://github.com/ParabolInc/parabol/pull/6407#discussion_r875507203_

**Comment by BartoszJarocki** [comment] 2022-05-19 08:19
`shortname` was intentional change, see discussion here: https://github.com/ParabolInc/parabol/pull/6068#discussion_r808404925

**Comment by Dschoordsch** [comment] 2022-05-19 08:39
> `shortname` was intentional change, see discussion here: [#6068 (comment)](https://github.com/ParabolInc/parabol/pull/6068#discussion_r808404925)

Fair enough, still the renaming DB->GraphQL should not happen in the DB layer. Also the case of the type should match the one we want (i.e. identifiers need quoting) so that we can get away with casting. Then we have a resolver for `Reactji.id` which just returns the `shortname`

**Comment by jmtaber129** [comment] 2022-05-19 15:43
+1 it would be nicer to have a dedicated SQL query for this. could even be just inline here.

_Originally posted by @Dschoordsch in https://github.com/ParabolInc/parabol/pull/6529#discussion_r876677939_

**Comment by Dschoordsch** [comment] 2022-05-20 11:04
Dataloader for
https://github.com/ParabolInc/parabol/blob/d8929e421d5db00d621d9eeec4b83287528e687f/packages/server/postgres/queries/getTeamPromptResponsesByMeetingIds.ts#L12

**Comment by jordanh** [comment] 2022-05-25 21:42
Marking as discussion and removing from backlog. Please re-add once we've got AC and EE added.

**Closed** 2022-12-20 20:01 UTC
Labels: discussion, icebox, chore

**Comment by jordanh** [comment] 2022-12-20 20:02
@Dschoordsch @BartoszJarocki @jmtaber129 iceboxing this one.

I think it would be a nice idea to open up a few issues that pay off specific bits of debt you sense we've accumulated vs. re-opening this one if you have tension caused by the closure of this issue
