### ISSUE TITLE
No GitHub repos displayed in push to integration dropdown

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#5717] opened 2021-11-26 14:50 UTC
**Steps to reproduce**

- Create a new account
- Make sure that there is no GitHub integration enabled, and no repositories displayed in the "push to integration" dropdown
- Add GitHub integration
- Try to push any issue to GitHub by opening "push to integration" dropdown
- See no repositories are displayed (make sure you have some on GitHub)

![image](https://user-images.githubusercontent.com/466991/143596918-16e5394a-2b6a-407d-88a1-52bec9b0d1e1.png)

**Environment:** PROD / Staging

**Comment by tianrunhe** [comment] 2021-11-29 18:48
Closing as it's a duplicate of #5612

**Closed by tianrunhe** 2021-11-29 18:48 UTC
Labels: bug
