### ISSUE TITLE
An error occurred, our developers have been notified

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4295] opened 2020-10-29 19:17 UTC
## Issue - Bug

[A client](https://app.hubspot.com/contacts/3888472/contact/9033151/) 🔒  reports:

For roughly 20mins, our entire team (roughly 40 of us) was getting the "An error occurred. Our developers have been notified. Please try refreshing the page."
I don't have a screenshot as I can't bring up the error anymore. It's ok now. But I hope it doesn't happen again. We wasted about 20mins refreshing during our company-wide townhall.

Time: Occured when ticket was submitted 6:15am (probably EST) Oct 21, 2020 in HubSpot 

Ticket: https://app.hubspot.com/contacts/3888472/ticket/228639142/

**Comment by gcrickman** [comment] 2020-11-04 16:24
Happened again at 5:17 AM EST

**Comment by jordanh** [comment] 2020-11-17 19:21
@gcrickman please continue to log additional instances of this happening from this customer, or any other. It will affect prioritization

**Comment by jordanh** [comment] 2020-11-17 19:21
AC
- [ ] investigate Sentry events, root cause triaged (and fixed if time allowed)
- [ ] if not fixed, new issue opened with what was learned

EE
4 hours

**Comment by gcrickman** [comment] 2020-11-18 14:49
[client](https://app.hubspot.com/contacts/3888472/contact/9033151/) 🔒  reports the same issue at 5:18 AM EST, screenshot is attached to ticket: https://app.hubspot.com/contacts/3888472/ticket/228639142/

**Comment by jordanh** [comment] 2021-05-04 00:10
This has long been fixed. Closing

**Closed by jordanh** 2021-05-04 00:10 UTC
Labels: bug
