### ISSUE TITLE
Outage between 10:06 and 10:14 CT on 2021-12-09

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5760] opened 2021-12-09 16:42 UTC
There was a PONG message in slack noticing the issue and a restart at 11:14 solved the issue.
Stats when logging in:
```
System load:  0.04
Usage of /:   69.2% of 98.30GB 
Memory usage: 29%
Swap usage:   0%
Processes:    176
```

**Comment by Dschoordsch** [comment] 2021-12-09 17:36
[`SEND TO SENTRY Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.`](
https://app.datadoghq.com/logs?query=status%3Aerror&cols=host%2Cservice&event=AQAAAX2f8cAt6dXOJwAAAABBWDJmOGNBd0FBRDZBMWgxRkp5dGRBQUE&index=%2A&messageDisplay=inline&stream_sort=desc&from_ts=1639065916770&to_ts=1639065989653&live=false)

**Comment by jordanh** [comment] 2021-12-14 19:16
## Bug

### Acceptance Criteria
   - Root cause explored and fixed, root cause with issue created, or conclusion of investigation communicated

### Estimated effort
   - 13 hours

**Comment by jordanh** [comment] 2022-01-04 19:39
Closing for now. Will reopen if/when this happens again

This was _not_ blowing past the postgres connection pool. _That_ happened when we restarted the server.

**Closed by jordanh** 2022-01-04 19:39 UTC
Labels: bug, p1

**Comment by adaniels-parabol** [comment] 2022-01-04 19:41
Outage documentation can be found here https://www.notion.so/parabol/2021-Dec-9-Outage-89ef235821884cc697b17b71426d3ba4
