### ISSUE TITLE
Sprint Poker: selecting 50 issues then deselecting won't clear error message

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4855] opened 2021-04-01 22:29 UTC
## Issue - Bug
Repro:
1. Start a poker meeting, go to scope phase
2. In one of the tab, check "Select next 50 issues"

There are two issues:
1. As soon as you check that checkbox, you will see the "Story limit reached" error, which seems confusing: if the app lets me select the next 50 issues then why would it be angry at me when I actually did that?
2. Even if the checkbox was unchecked, the error stays

![2021-04-01 15 23 48](https://user-images.githubusercontent.com/1879975/113360498-c3d81980-92fe-11eb-9c3e-24556166b67e.gif)

### Acceptance Criteria (optional)
- [ ] User has clear understanding on the limit of stories we support and we give them appropriate and accurate information

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment] 2021-05-18 16:26
promoted to P2 as we'll want to fix this before we duplicate the buggy code to github

**Comment by tianrunhe** [comment] 2021-05-21 07:59
I **can't** reproduce the "story limit exceed" error any more in production. The only issue right now is that selecting 50 issues altogether takes a while to process. As a result, if a user mistakenly click the checkbox and wants to immediately uncheck it, the app won't respond.

**Comment by mattkrick** [comment] 2021-05-25 21:00
Hmmm, nothing changed, so i'm guess the bug is still there?

I'd hope that clicking that box back to back is an edge case, better than have them accidentally click it twice & removing what they just created. If you can repro again lemme know!

**Comment by BartoszJarocki** [comment] 2021-06-22 19:26
@tianrunhe @mattkrick I did my best but I still couldn't reproduce it. I'm going to close it. If we spot it again, I'd be happy to get back to it. 👍

**Comment by mattkrick** [comment] 2021-07-23 17:39
Found the bug!
i didn't account for the number of dimensions :facepalm: 

`if (stages.length > Threshold.MAX_POKER_STORIES * dimensions.length) {`

fix in #5205

**Closed** 2021-07-24 00:48 UTC
Labels: bug, p2
