### ISSUE TITLE
Store `issueId` instead of `issueNumber` for GitHub issue integration

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6252] opened 2022-03-22 15:43 UTC
## Issue - Refactoring

Currently, our GitHub integration hash consists of `${nameWithOwner}:${issueNumber}`.

However, when doing API requests to GitHub we must provide `issueId`, not the `issueNumber`.
For example, for adding a comment: https://docs.github.com/en/graphql/reference/input-objects#addcommentinput

This leads to additional queries to get the issue id:

https://github.com/ParabolInc/parabol/blob/e1a99845a7f799b30d08f7a08412cf35e5c0afc6/packages/server/graphql/mutations/helpers/pushEstimateToGitHub.ts#L75-L82

I see 2 possible solutions:
- Store `issueId` in integration hash
- Store `issueId` in the database directly

I would suggest considering 2nd solution: No need to rewrite all the hashes. No need to perform split/join to get necessary data. See related discussion here: #5968

AC:
- [ ] Write a migration that fills data for existing issues (if possible), or use a fallback
- [ ] Use `issueId` in code instead of fetching it from the API

**Comment by jordanh** [comment] 2022-03-22 18:21
Duplicate of #5427, but I find your AC clearer. I will keep this issue open and prioritize to the backlog and close the other

**Closed** 2022-12-20 20:14 UTC
Labels: enhancement, icebox, Story Points: 13
