### ISSUE TITLE
Can't access meeting summaries

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5125] opened 2021-07-12 17:08 UTC
## Issue - Bug

This [user](https://app.hubspot.com/contacts/3888472/contact/34678001) 🔒 cannot access meeting summaries for completed meetings, the email summary is also blank. The discussion can also not be accessed from the meeting cards on their timeline. 

> I am trying to view and export a meeting summary from a previous meeting, but anytime I click on the "review a summary" link for any of my meetings, it just takes me to this screen:

![image](https://user-images.githubusercontent.com/60167404/125328257-1bc8e800-e312-11eb-890a-e1d6bae66e6e.png)

Hubspot ticket: https://app.hubspot.com/contacts/3888472/ticket/477054567/

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tiffanyhan** [comment] 2021-07-12 18:47
This is not an edge case, it's also happening for Parabol organization (i.e. clicking on meeting summary from Timeline redirects to Meeting view) so it's safe to say it's affecting all users of the app. check-in meetings are fine, but retros and pokers are not.

in the retro case, it looks like `reflectionGroupId` is missing from meeting => stage => phase objects. see sentry error below. We have 110 events so far since Jun 14, so it doesn't look like a new error.

https://sentry.io/organizations/parabol/issues/2449549409/?project=107196&query=is%3Aunresolved+reflectionGroupId&statsPeriod=14d

**Comment by tiffanyhan** [comment] 2021-07-12 18:53
this issue is a duplicate of https://github.com/ParabolInc/parabol/issues/5099

**Comment by BartoszJarocki** [comment] 2021-07-13 07:56
Sentry issue: [ACTION-PRODUCTION-80J](https://sentry.io/organizations/parabol/issues/2449818299/?referrer=github_plugin)

**Comment by mattkrick** [comment] 2021-07-13 18:34
closing in favor of #5099

**Closed by mattkrick** 2021-07-13 18:34 UTC
Labels: bug, p2
