### ISSUE TITLE
people accidentally advancing through retro phases then can't go back 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4881] opened 2021-04-12 19:57 UTC
A [user](https://app.hubspot.com/contacts/3888472/contact/10336201) 🔒  writes: 

> Since her team is not used to the tool yet, they often advance to the next phase too soon and then are unable to go back. I believe what they do is that the facilitator clicks “Next” assuming he is just doing it for themself, without being aware they will be forcing everyone to move to the next retrospective phase right away, and then I guess they can’t go back.

**Comment by drewhousman1010** [comment] 2021-04-19 14:07
A [user](https://app.hubspot.com/contacts/3888472/contact/14061851) 🔒  writes:

> I'd like the possibility to undo step-forward (happened now several times to me with my new teams that we end up needing to go a step back after completing a phase)

**Comment by drewhousman1010** [comment] 2021-04-19 22:07
A [user](https://app.hubspot.com/contacts/3888472/contact/19750501) 🔒  says:

> New facilitators tend to click on steps in the sidebar and it progresses meeting to next steps as if a phase was completed. Then they struggle to go back. A clearer warning that clicking around on the sidebar will advance the retro would be nice.

**Comment by jordanh** [comment] 2021-04-20 18:21
It is possible to reset the Grouping phase today. If you've advanced from Group to Voting, then input some votes, you can navigate back to Group and drag cards around. Doing so will prompt the facilitator to ask if they'd like to reset the meeting.

We implemented some friction on the bottom bar, making it more difficult for folks to advance the meeting unless a phase had received proper input.

What might be necessary here is to introduce some friction on the side bar.

Promoting this to a discussion to spool up some ideas for what we might want to do if this keeps coming up

**Comment by drewhousman1010** [comment] 2021-05-19 18:09
A [user](https://app.hubspot.com/contacts/3888472/contact/2140401) 🔒 said: 

> When a dev has to lead a meeting for the first time, they are always hitting next and then can't go back. A little alert like "are you sure you want to go to the next phase?" would help

**Comment by drewhousman1010** [comment] 2021-06-03 14:41
A [user ](https://app.hubspot.com/contacts/3888472/contact/9652601) 🔒 says:

> When new users facilitate on Parbaol they will accidentally move forward phases. This is especially bad when voting is not done. I wish there was a way to reset the votes at the vote stage instead of going all the way back to the groups phase

**Comment by drewhousman1010** [comment] 2021-07-06 18:48
A [user](https://app.hubspot.com/contacts/3888472/contact/19720001) 🔒 says:

> I was running a retro and during the voting section while others were voting, I clicked into the Discuss section just to see what was in there and it abruptly ended the voting session, which was a bummer.
> 
> Just some feedback on that -- I wish I had the ability to undo a phase completion.

**Comment by igorlesnenko** [comment] 2021-11-02 19:34
Just run into this issue myself. I started a meeting and gave people 2 days to post reflections. At some point, I by accident clicked on the "Group" link on a sidebar and made reflections visible. 

So it caused 2 issues:
1) I had to recreate the meeting.
2) Some anonymous reflections were shown ahead of time. 

I wish I had some confirmation when clicking a link in the sidebar

**Comment by drewhousman1010** [comment] 2022-01-10 17:00
A [user](https://app.hubspot.com/contacts/3888472/contact/24011901) 🔒  says:

> When we finish a phase we can't go back. This happens most often with people who are new to Parbaol and facilitating their first meeting. It would be nice to have the ability to go back to a previous phase and make changes.

**Comment by nickoferrall** [comment] 2022-03-01 15:02
A [user](https://app.hubspot.com/live-messages/3888472/inbox/2263605263#live-chat-reply-editor) 🔒 says:

> I mistakenly advanced to Groups before the meeting has even started.  How can I get back to "reflect"

**Comment by jmeridth** [comment] 2022-05-17 17:26
I, as the facilitator, accidentally advanced from `Reflect` to `Group` and when I went back to `Reflect` a status says `phase completed` and you can no longer use the Timer.  You can still add items but would be nice to unmark a phase as completed.  (I'm aware PRs are welcome and will look at this).

Great tool otherwise.  Thank you.

**Comment by drewhousman1010** [comment] 2022-07-13 13:58
An [enterprise customer](https://app.hubspot.com/contacts/3888472/contact/67054151) 🔒 writes:

> We are in a retro and somehow accidentally "completed" the Reflect phase, is there a way to reset it? 
> 
> It seems very easy to move forward in the phases (clicking on the left sidebar) and get stuck with no way to go back 
> 
> This is a longer-standing async retro and it would be a pain to have to create a new Parabol meeting and migrate the existing cards over
>

**Comment by igorlesnenko** [comment] 2022-09-14 16:53
I pushed a PR with possible solution #7181

**Comment by acressall** [comment] 2022-09-14 17:08
I think this is a nice, simple solution! I'm guessing @ackernaut might have more thoughts about phase order in relation to structured conversations, but this makes sense to me for the current structure

**Comment by enriquesanchez** [comment] 2022-09-14 20:44
Seeing that it's the same behavior currently available for the grouping phase, I think this is safe to try. As for the warning text, I suggest to avoid the line break of the last sentence, and maybe set `will be lost` in bold as well?

That said, this is the first time I see this piece of UI (the option to edit groups), is it new? 

I know this is probably out of scope here, so feel free to ignore me, but I wonder if there's a chance to tweak it a little? I think we can improve this component and streamline it into a single component for clarity and simplification:

<img width="641" alt="Captura de Pantalla 2022-09-14 a la(s) 3 32 32 p m" src="https://user-images.githubusercontent.com/3276087/190256771-fdb490d0-ce6b-48c4-83ea-fd7bf655b748.png">

The 1st and 2nd options are pretty much the same style of component, only adding the option to `Edit` inline into the phase state notice.

The 3rd one is a newer style we've been exploring for standups, but we haven't implemented yet.

@acressall @ackernaut Would love to hear your thoughts here. We'd probably need to update this component in other places. @ackernaut I know [you had previously mentioned that you liked the style direction of this pill-shaped notice](https://www.figma.com/file/fw5gj7qRbKSh5XQbnh0PUr/Standups-tweaks?node-id=273%3A29086).

**Comment by igorlesnenko** [comment] 2022-09-15 08:31
Posting @mattkrick comment here to keep discussion in one place https://github.com/ParabolInc/parabol/pull/7181#issuecomment-1247147374

> My .02:
> 
> * From a psychological standpoint, when a meeting goes backwards instead of forwards, it feels bad. Speaking for myself, whenever the person leading a meeting says "let's go back and redo..." I disengage. The root cause here is that the facilitator moved forward before the team was ready. Preventing them from making a mistake is always preferable to allowing them to undo the mistake!
> * Why does the facilitator move forward before everybody is ready? If everyone else hasn't clicked the "Ready" button, then when the facilitator clicks "next" they get a tooltip and have to click "next" again to move forward. _This_ is the area that's broken! Is the tooltip unclear? How could we make the words more meaningful? Do we say "Is everyone ready? If so click next again". Should we specify that if they move forward they can't move back? Do they know that the team can still add reflections in the group phase?

This make sense to me, I see two possibly more common issues

- There is no friction on sidebar at all, very easy to go forward
- `Tap Next again to confirm` tooltip may not be clear enough because it doesn't say they can't go back

What is possible to do here is:
- Add a confirmation dialog when user click on sidebar.
- Change `Next` button tooltip message, or use confirmation dialog too.

@enriquesanchez what do you think?

**Comment by mattkrick** [comment] 2022-09-15 20:26
> There is no friction on sidebar at all, very easy to go forward

Heh, we used to have friction here! It used to be that you couldn't advance to the next phase via the left nav. I believe we removed it in the last year or so to allow folks to move forward friction free :smiling_face_with_tear:.

> Add a confirmation dialog when user click on sidebar.

I think that's great! My only suggestion would be to have it be smaller than a full on dialog. maybe the same tooltip that you get from clicking "next"? it'd be great if clicking left nav & clicking "next" following the same chain of logic (e.g. trying to progress without everyone being ready pops up a tooltip & requires a double click)

> Change Next button tooltip message, or use confirmation dialog too.

I'm a fan of testing out different messaging! 100% agree `Tap Next again to confirm` is probably a little too vague. Maybe `Tap Next again if everyone is ready`? 

 IMO a dialog that makes folks move their mouse to click it might be _too_ much friction, especially for async meetings. I'd opt for better messaging & then if the problem doesn't go away we can revisit adding more friction later

**Comment by enriquesanchez** [comment] 2022-09-15 22:28
@igorlesnenko I have to say that this was the first time I found we have this option for editing groups, so I'm new to this feature, and as such I'm discovering how it works.

I'm a bit confused because I just found out that currently users are able to add more reflections once they select that  `Edit groups` option. See this Loom for a demo:

https://www.loom.com/share/e5b1c1f0463f4818a68b76440c133158

So I wonder if we should just change the language of the `Edit groups` option to reflect that they can also add reflections once they "unlock" the grouping phase?

And if the problem is that they move from `Reflect` to `Group`, I think the issue is that it's probably not so obvious that they can still add reflections in the grouping phase, right? 

<img width="1262" alt="Captura de Pantalla 2022-09-15 a la(s) 5 20 18 p m" src="https://user-images.githubusercontent.com/3276087/190518874-33beeab3-110a-4321-a142-aeed2d278bba.png">

**Comment by garethaledavies** [comment] 2022-09-21 14:13
A [user](https://app.hubspot.com/contacts/3888472/contact/79582151) in a research call said that her least favourite thing about Parabol is that:

> If you go through one stage, you can’t go back (even if you grouped something wrongly)

And that this causes problems for first time facilitators, and the first time you run a Parabol meeting and don't necessarily know 100% how it works.

**Comment by igorlesnenko** [comment] 2022-09-30 14:53
@enriquesanchez Yes, I think the things you mentioned may be one of the reasons why users have problems

1) I think we can change 'Edit groups' to make it more clear. Do you have an idea what text to use here? If we just change it to 'Edit' like on earlier mockups, would it be better?

2) We can also make ability to add reflections in Group phase more obvious. Maybe replace '+' sign with 'Add' button?

Along with this, I think we still need to implement other solutions. As there are also other problems:

- Exposing anonymous reflections ahead of time, no way to use timer again, they have to add visible reflections in a real time
- To fix accidental advancing from Vote to Discussion they need to reset all the groups.

I think If we prevent users from advancing by an accident, it probably will solve all the cases. Of course, if it is could be prevented completely at all.

I put on hold my PR with resetting a meeting, and tried to add a friction to the sidebar, because sidebar is really not obvious thing and I personally got caught up in it too. I also tried to change the 'Tap Next' message


https://user-images.githubusercontent.com/466991/193296964-9ad2733e-b17f-41ed-b52a-d42f5003dfaa.mov

@enriquesanchez  What do you think?
cc @mattkrick

**Comment by enriquesanchez** [comment] 2022-10-03 18:30
@igorlesnenko I think the tooltip on the sidebar is a nice addition. It's pretty much the same behavior that you get if you would click on `Next`.

**Comment by jordanh** [comment] 2023-04-14 23:08
[A user](https://app.hubspot.com/contacts/3888472/contact/84521201) 🔒 writes:

> I often hit the next button by mistake. Is there a way to make that clearer that it's going to cut off the previous phase? Or to reactivate? What I find is when I'm the meeting facilitator, I never know if I should click it to indicate I'm done or I'm waiting for everyone else only and then clicking next.

**Closed** 2023-10-24 09:19 UTC
Labels: enhancement, discussion, icebox, Story Points: 13
