### ISSUE TITLE
Ad-blocker partially break Parabol web application

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#5252] opened 2021-08-05 18:22 UTC
First detected with Ublock origin (ad blocker), ad-blockers seem to partially break the Parabol web application. A user running an ad-blocker couldn't logout, view profile, or browse past the initial screen.

Things to consider, should we detect ad-blockers and display a model. Here's a handy node module https://www.npmjs.com/package/adblock-detect-react

**Action item: Further research is needed to determine the extent and exact nature of the break.**

**Comment by jordanh** [comment] 2021-08-08 21:45
Added to team agenda to discuss

**Comment by jordanh** [comment] 2021-08-10 16:39
AC
- [ ] Reproduce failure using ad blocker
- [ ] Create one or more issues for how to resolve usage of ad blockers being fatal to product experience

EE
- 16 hours

**Comment by adaniels-parabol** [comment] 2021-08-10 16:44
![image](https://user-images.githubusercontent.com/71724289/128899843-1f1ae76d-568f-4138-82b1-c4651c052409.png)

**Comment by adaniels-parabol** [comment] 2021-08-10 17:23
This is the console when it breaks.
![image](https://user-images.githubusercontent.com/71724289/128906027-5940ad12-17a6-41bf-b1fd-df343e9a2a24.png)

**Comment by adaniels-parabol** [comment] 2021-08-10 17:36
When it breaks, I seem to randomly get a block on precache files https://action-files.parabol.co/production/build/v6.23.1/precache-manifest.db761e2a679db17cb49fae933e827f2d.js

**Comment by adaniels-parabol** [comment] 2021-08-10 18:02
Disabling ad-blocker seems to solve the issue (when it occurs, it's sporadic)

**Comment by mattkrick** [comment] 2021-08-11 16:28
once we can reproduce, we should probably first look in the sw.js file to see if we can introduce a try/catch or similar to gracefully fail.

**Comment by nickoferrall** [comment] 2021-08-18 22:56
I installed the [Ublock extension](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm/related?hl=en) on Chrome, Brave and Firefox but I haven't been able to reproduce this one yet. 

You mentioned that it happened sporadically @adaniels-parabol. Just wondering if the bug has cropped up again since last week or if you're still able to reproduce it?

Would love to know if anyone else can repro it after installing the extension

**Comment by mattkrick** [comment] 2021-08-19 00:51
@nickoferrall have you been testing in prod or locally?

current thinking is that logrocket may be the culprit. could you try turning logrocket on locally & maybe setting the flag in your local storage? segment could be at fault, too, so make sure all those fun analytics script file try to load but fail in the dev tools

**Comment by nickoferrall** [comment] 2021-08-19 20:41
@mattkrick I was testing in prod - I just tried testing locally with LogRocket on and the error prone flag on but didn't reproduce the error.

I removed the dev [flag](https://github.com/ParabolInc/parabol/blob/d6131e37fa80e09e0b5e7672e8088a5d61eeb220/packages/client/components/AnalyticsPage.tsx#L52) in the AnalyticsPage and could see the Segment `useScript` hook was failing to load as the key is undefined locally. After changing it to the valid string, it fails to load with a console err of `ERR_BLOCKED_BY_CLIENT`.

In prod, I can see that LogRocket and Segment are throwing warnings and errors:

![console-err](https://user-images.githubusercontent.com/39854876/130140633-bcc66fd9-811d-4d6c-a585-9ce19a159b1f.png)

**Comment by nickoferrall** [comment] 2021-08-19 20:41
I can assign this issue to myself unless anyone else wants it. It'd be great to know if anyone can repro the error after downloading the Ublock extension

**Comment by nickoferrall** [comment] 2021-08-19 21:49
This issue may be related to https://github.com/ParabolInc/parabol/issues/5282. 

Next steps:

1. See if other Product team members can repro the issue
2. See if Matt's upgrading Relay work will help with this issue

**Comment by mattkrick** [comment] 2021-08-30 18:01
yeah, i think we've given it enough time to try & reproduce. If we hit it again organically we can re-open

**Closed by mattkrick** 2021-08-30 18:01 UTC
Labels: bug, p1
