### ISSUE TITLE
Updating a CC upgrades to pro automatically

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5300] opened 2021-08-20 21:17 UTC
## Issue - Bug

To reproduce:
- [ ] upgrade an org to pro
- [ ] downgrade the org to personal using `downgradeToPersonal` mutation
- [ ] go to the org page, where you can find CC info
- [ ] change the CC info using any one of these [alternate test numbers](https://stripe.com/docs/testing#cards)
- [ ] observe that the org will be upgraded to pro

### Acceptance Criteria (optional)
Users can:
   - [ ] repeat the above steps and the org shouldn't be upgraded to pro

**Estimated effort:** 4 hours. More if root cause is already identified.

**Comment by mattkrick** [comment] 2021-08-24 18:07
oh this is great.
we should probably nuke the last4 & card type when they downgrade. that'll keep that stuff hidden in the UI.

**Comment by jordanh** [comment] 2022-03-01 19:40
When grooming this one, we were confused by the AC to resolve it.

We think the heart of the issue is that after downgrading the CC info remains. Therefore, a more reasonable fix for this would be to make sure the `downgradeToPersonal` mutation removes the last4, etc. CC info from our DB.

Acceptance Criteria (optional)
- After downgrading an account, any CC meta information is removed from the DB
- Optional: Subscription fires to update anybody viewing this form

EE
- 5 hours

**Comment by jordanh** [comment] 2022-08-30 19:27
Third time scrubbing. Going to take a hint and icebox. I am sure this will come back up

**Closed by jordanh** 2022-08-30 19:27 UTC
Labels: bug, icebox, p2
