### ISSUE TITLE
extracting the csv file before the meeting ends 

### ISSUE THREAD

**Issue by thaywood83** [ParabolInc/parabol#5244] opened 2021-08-02 19:04 UTC
## Issue - Enhancement

A [user 🔒 wrote the following feedback](https://app.hubspot.com/contacts/3888472/contact/39183551):

> I have a "meeting" in process - moved from Reflection to grouping but I want to pull the data out into a CSV/excel file to do some more summarization into an executive overview slide -- I am not seeing how to do that without "ending" the session - as I know when ending it all members receive the report out and we are not ready to do that yet.

> I recommend that you put on your enhancement roadmap an "export data" button -- the content is there - should be able to access it.   In the interim I wish that you all had a way to pull the data out of your server and send to me 

> Context/backstory: We are trying to do an grouping and theming for feedback with a smaller core team prior to full team review

> Context/backstory: We did a soft launch of a new Sales and Operations Effectiveness process across our Supply Chain organization - we are readying to expand the effort to include our Finance and Commercial organizations - we are trying to synthesize the feedback from the Supply Chain teams to provide insight to the other leadership teams to aid in furthering the design of the process -- but also need the feedback to plan and propose interim improvement processes for current phase. (lots of different stakeholder teams.

**Comment by jordanh** [comment] 2021-08-05 04:34
Duplicate of #5244, closing this one

**Closed by jordanh** 2021-08-05 04:34 UTC
Labels: discussion, enhancement
