### ISSUE TITLE
Card editor: font size formatting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#1106] opened 2017-06-22 22:14 UTC
## Enhancement

Users can select text and use keyboard shortcuts to cycle up and down predefined font sizes. 

(credit: inspired by Gmail)

- [ ] Sizes are small, normal, large
- [ ] `command + shift + plus` cycles up in size
- [ ] `command + shift + minus` cycles down in size

<img width="324" alt="font sizes 2x" src="https://user-images.githubusercontent.com/307286/27490328-77279604-5803-11e7-96b8-a4bcb55a5b17.png">

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by p-parafiniuk** [comment] 2018-02-15 08:32
Hi, I would like to do this task for 13 points.

**Comment by jordanh** [comment] 2018-02-15 16:01
Hey there @p-parafiniuk – the issue is now yours for 13 points. We've updated the [E4E Project Board](https://github.com/ParabolInc/action/projects/1) and marked this issue as "Building". If you have any questions, please join our [developer slack](http://slackin.parabol.co/) and reach out.

Since this is your first contribution, we'll need to shoot you over an agreement before we merge your PR or tally up your points. Could you write me at `jordan` `@` `parabol.co`?

Thank you for helping us out!

**Comment by ackernaut** [comment] 2018-02-15 16:23
( psst this one is also available for E4E #1512 )

**Comment by mattkrick** [comment] 2018-02-15 16:25
That sounds right  @p-parafiniuk! 
Would you mind building it as a new `withFontSizes` HOC? That way we can apply it to the other draft-js editors we have floating around the app. An example HOC is here: https://github.com/ParabolInc/action/blob/master/src/universal/components/TaskEditor/withKeyboardShortcuts.js

Feel free to add it to the current `customStyleMap.js` and plug that in.
As @ackernaut mentioned, after that's built, #1512 should only take a couple minutes to implement.

**Comment by p-parafiniuk** [comment] 2018-02-16 12:32
@mattkrick 
Thank you for the tips I will check this out and will apply another HOC for this solution, hence I will probably move on to #1512 as @ackernaut suggested
 
PS: do you have any particular code of conduct for: 
1. creating commit/branch names
2. formatting source code (eg. Prettier)

**Comment by jordanh** [comment] 2018-02-16 14:46
We don't presently have an established rule for how to name branches. I'd suggest something like `cart-font-formatting-1106`

On source code, our formatting guidelines are covered by our linting rules (`npm run lint`).

Enjoy!

**Comment by jordanh** [comment] 2018-02-16 21:52
Realized this should be in the "Scope & Bid" phase until we get the E4E agreement settled :)

**Comment by dpeletz** [comment] 2019-03-27 12:02
Hi, I would like to complete this task for 13 points.

**Comment by jordanh** [comment] 2019-03-27 16:04
@dpeletz great to have you. Confirmed! It's yours for 13 points.

Start by joining our [developer Slack](http://slackin.parabol.co/) and cloning this repository. After you get the dev environment set up, we recommend creating a pull request to us as early as possible so we can give you feedback as you go along.

Welcome aboard!

**Comment by jordanh** [comment] 2019-11-12 17:51
Reopening issue, @dpeletz was unable to complete. Looking forward to another great community member to take a stab at this!

**Comment by mattkrick** [comment] 2019-11-12 23:12
Note we'll want to implement this in atlaskit, not draftjs, so this is stuck behind #3324

**Comment by eng-almeida** [comment] 2020-03-10 12:58
Hi, I would like to take this task. Is it still blocked by #3324 or can I proceed?

**Comment by mattkrick** [comment] 2020-03-10 15:51
hey @eng-almeida! Correct, still blocked by #3324, which is probably ~60 hours of work to reach feature parity of what we have in draft-js. That said, happy to discuss the migration to prosemirror if you're up for it!

**Comment by mattkrick** [comment] 2021-09-23 16:08
Closing as we'll just want to wrap this up in our new wysiwyg editor implementation

**Closed by mattkrick** 2021-09-23 16:08 UTC
Labels: enhancement, help wanted
