### ISSUE TITLE
Conversion Prompt only interrupts facilitators holding meetings in Orgs that need to upgrade 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3808] opened 2020-05-01 17:32 UTC
## Issue - Bug

Currently, if a user is part of an org that has the conversion prompt turned on, and they facilitate a meeting, they'll see the conversion prompt. 

However, users can be part of multiple orgs, some with the prompt turned on and some without. 

Ideally, if the meeting they're facilitating isn't for the Org that needs to upgrade, they would **not** see the conversion prompt. 

### Acceptance Criteria (optional)
Users can:
   - Facilitate a meeting for an Org without conversion prompt turned on and won't see the conversion prompt, even if some orgs they're part of do have the prompt turned on
   - Triaged and fixed, or triaged and new issue opened

- **Estimated effort:** 16 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

NOTE: @jordanh and added EE and additional AC

**Comment by avivapinchas** [comment] 2020-05-05 20:30
Just logging more deets, in case it's helpful: I got the conversion prompt again during a retro with Carlos as part of his BP.

**Comment by jordanh** [comment] 2020-05-26 17:30
Scrubbed!

**Comment by jordanh** [comment] 2020-07-08 22:42
@shawneeatparabol ran into this one too, she has [a customer](https://app.hubspot.com/contacts/3888472/contact/12228101) who upgraded, who still sees the modal. Why? Because we're asking a peer of his to upgrade too, and he also belongs to that peer's org.

**Comment by tiffanyhan** [comment] 2020-07-16 00:01
After looking into this, it seems to me that @avivapinchas vs @jordanh + @shawneeatparabol are talking about two different issues.

1. Aviva's issue seems to map to the `flagConversionModal` action. This conversion prompt will only appear before proceeding to the "Discuss" phase of a Retro meeting. If I'm understanding the issue correctly, I am so far unable to reproduce this bug. This conversion prompt only appears for me when I'm in a meeting of an organization that has yet to upgrade (as expected). The conversion prompt will disappear when the org is upgraded.

<img width="897" alt="Screen Shot 2020-07-15 at 4 38 48 PM" src="https://user-images.githubusercontent.com/11562889/87610240-b2d87100-c6b9-11ea-9511-2b9b2e0e84ec.png">

2. Shawnee and Jordan's issue maps to the `flagOverLimit` action. This prompt will appear on pretty much *every* screen, as it belongs to the global "Dashboard" object. Contrary to the prior prompt, which is based on a set `Organization` level field , this prompt relies on the `User.overLimitCopy` field. Note that even though the action takes an `org` param, the resolver applies the flag to each and every `User` belonging to that org. So, if a user belongs to *any* organization which has this action applied to it, they will see the prompt on every screen, even on screens scoped to already upgraded orgs. Additionally, this prompt will not automatically disappear when the org is updated. The prompt can only be removed manually by unsetting it in graphiql.

<img width="897" alt="Screen Shot 2020-07-15 at 4 43 09 PM" src="https://user-images.githubusercontent.com/11562889/87610481-4b6ef100-c6ba-11ea-9e77-4941a5b89bb5.png">

To fix the issue, I propose putting the `overLimitCopy` field on the `Organization` level instead of `User`. We can then show the prompt when the user is in any of: (1) any action or retro meeting of the org to update; (2) any team pages of that org; (3) that organization's pages. I propose showing the prompt in all 3 areas. I believe we should also auto-magically unset the flag when the org is updated.

@mattkrick @ackernaut what do you think? lmk if you have anything to add.

**Comment by avivapinchas** [comment] 2020-07-16 15:50
Ah sorry for the lack of clarity in my initial comment - I didn't realize these things functioned differently. My issue is the same as the one that Jordan and Shawnee are reporting.

**Comment by tiffanyhan** [comment] 2020-07-16 17:11
@avivapinchas Oh perfect! I was getting worried that I couldn't reproduce what I thought was the first bug. Thanks for clarifying!

**Comment by mattkrick** [comment] 2020-07-16 18:13
@tiffanyhan a little background on this one, we did a quick & dirty by just putting this flag on the User object.
Now that we have actual sales & marketing people, we should take the time to do this right.
So, I'd suggest the following AC (feel free to adapt as needed):

- In the DB & the GraphQL schema, the OrganizationUser has an optional `overLimitCopy` string field
- The `User` object in the GraphQL schema looks up the `overLimitCopy` for each associated `OrganizationUser` and picks the first one
- `flagOverLimit` mutation edits the OrganizationUser instead of the User

**Comment by tiffanyhan** [comment] 2020-07-16 18:50
@mattkrick thanks for the additional context! i'm curious what the reasoning is for wanting to put `overLimitCopy` on `OrganizationUser` rather than `Organization`? also from the AC you proposed, i'm not seeing how accessing `overLimitCopy` from `User` object in GraphQL schema would help with only showing the copy on only properly scoped views.

**Comment by mattkrick** [comment] 2020-07-17 01:03
ah, hold off on this @tiffanyhan I'm still uncertain what folks want.


@avivapinchas @jordanh @shawneeatparabol 
we need some clarity here. today, we've got 2 separate thorns:
- `showConversionModal`. This pops up a modal mid-meeting for any team who is a part of an org with the flag set. It asks for their credit card.
- `overLimitCopy`. This pops up a snackbar at the bottom of their screen telling them to contact us. if they close it, it re-opens 5 mins later.

This issue is for `showConversionModal`. I believe this is working as intended & that the issue can be closed. If the problem is for the `overLimitCopy`, please open a new issue so we can address it there.
If this is _not_ working as intended, can you please include the organization affected so we can triage?

**Comment by avivapinchas** [comment] 2020-07-17 01:07
Apologies again for the confusion - I use 'conversion prompt' interchangeably to mean either the mid-meeting modal or the snackbar. I'll try to be more precise with this in future! 

This issue _is_ for the snackbar, as discussed with @tiffanyhan up [above](https://github.com/ParabolInc/parabol/issues/3808#issuecomment-659502008) - happy to open another issue, but seems redundant?

**Comment by mattkrick** [comment] 2020-07-17 01:23
gotcha. in that case, this is going to either be a _lot_ of work, or be a band-aid on a knife wound. Before moving forward, I want to make sure that this is the target implementation, because for the amount of time we invest in this, we could build something else that's even better.

today, the snackbar is dumb, it doesn't know what page its on, it just pops up on repeat.
if we want to make it "aware" of the page it's shown on, we can't just stop at a meeting. If we did, the next complaint will be "how come this shows up on my team dash? i paid for _this_ team!" same for the organization dash, invoice preview, etc. we'll essentially need to make _every_ single route in the app "aware" and keep that up to date as new features are added. that's nasty.

**Comment by mattkrick** [comment] 2020-07-17 01:32
few alternatives:
- user/company specific messaging. "Hey Matt, your organization Cheapo needsto

**Comment by mattkrick** [comment] 2020-07-17 01:36
few alternatives that are simpler to implement:
- company specific messaging. "Hey Matt, it's time you upgrade CheapoOrg" and just have that show up everywhere. Big picture, if they have this nag turned on _they're doing something wrong and being in a paid meeting shouldn't excuse that_
- Only turn the nag on for billing leaders
- Only turn the nag on if the user is not a member of a paid organization

**Comment by tiffanyhan** [comment] 2020-07-17 18:55
Hey matt, thanks for the alternatives. I'm not a proponent of the second one, "Only turn the nag on for billing leaders
". I don't think it would address Shawnee's person's problem, which is basically that they upgraded but are still seeing the snackbar prompt because they are part of another org that needs to upgrade.

The other two would definitely be less work to implement than making the snackbar "aware". It seems like the question boils down to: Should the person not be seeing the snackbar prompt at all, or is it fine that they're seeing the snackbar prompt but it needs to be org-specific to eliminate confusion? @shawneeatparabol @jordanh @avivapinchas 

Depending on what people want, the 1st or 3rd alternative you suggested would work. For the 1st one, it can either be completely up to the salesperson to manually enter in an org-specific prompt *or* we can have one generic message generated with the org name combined with a custom "please contact ____". The 3rd alternative seems straightforward, and would mean that any member (billing leader or not) who is part of a paid org will not see the snackbar prompt.

**Comment by avivapinchas** [comment] 2020-07-17 20:39
@jordanh @shawneeatparabol  Do we foresee someone potentially being the billing leader for 2 different orgs that we want to convert? Seems like a niche case to me, but y'all are closer to it. If it is a niche case, then #3 makes sense to me.

**Comment by mattkrick** [comment] 2020-07-17 21:25
Another option:
- turn the snackbar nag on _only_ in the meeting. the downside to this is the nag just isn't as naggy.

**Comment by avivapinchas** [comment] 2020-07-17 21:40
I'm not a fan of this because I think folks are less likely to act during the meeting, and the nag tells you to contact someone currently. Also, we already have the interrupting thingy during the meeting, so feels like that's covered.

**Comment by tiffanyhan** [comment] 2020-07-20 18:01
@shawneeatparabol @jordanh imo, it seems like solution no. 3 best addresses the tension that folks are having. If there are no objections, I will move forward with matt's suggestion no. 3: `Only turn the nag on if the user is not a member of a paid organization`.

**Comment by jordanh** [comment] 2020-07-20 19:04
I agree with @shawneeatparabol, I think option 3 is a good balance between quick and taking us where we want to do. With this input, what do you think @tiffanyhan ?

**Comment by tiffanyhan** [comment] 2020-07-20 19:12
cool, sounds like we're at consensus. i can implement solution no. 3!

implementation-wise, i think it would just be adding logic to `User.overLimitCopy` graphql field resolver so that it null if the user is a member of any paid org.

**Closed** 2020-07-21 20:52 UTC
Labels: bug
