### ISSUE TITLE
Custom Kanban Columns

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4610] opened 2021-01-28 22:55 UTC
## Client Request: Custom Kanban Column Headers

From a 🔐 [client](https://app.hubspot.com/contacts/3888472/contact/12975601):
"Our team has started to use our Parabol board for a range of different types of retro tasks that extend beyond simple action items and we're using columns to organise and visualize them.We'd love to be able to rename the columns - and even add additional columns to the team dashboard. In a similar way to how different teams use different names for their Trello board columns, and their Azure Devops board columns.

I think we might like something along the lines of:
Do this sprint (this would replace 'Active')
Do this quarter (this would replace 'Stuck')
Future / Todo / Maybe (one of those)
Done

One way that Parabol works well for us is that we are always looking to check off and complete tasks. We review our board regularly and if a card is in the active column longer than a sprint cycle it becomes apparent to the team that it's in a 'Stuck' or 'Stale' state and we usually discuss what we can do to move it along on our board. The 'Stuck' column is a little redundant to us as stuck items will always remain in the 'Active' column. 

We use Azure DevOps for work tasks and we use Parabol for retro / team agile process tasks. It seems to benefit us to keep these two areas of concern separated so we aren't looking for a way to transfer tasks to-and-from DevOps."

### Acceptance Criteria
Users can:
   - Team leaders can name the Kanban columns anything they want
   - Customize the number of columns per team board

**Comment by ackernaut** [comment] 2021-03-01 18:02
>Columns on KanBan board, change the status, limited space on card, would like to be able to comment on dashboard like a backlog item or change the column headers/add more

**Comment by gcrickman** [comment] 2021-03-24 16:29
A [user](https://app.hubspot.com/contacts/3888472/contact/13321151) 🔒  says:

> In the board where you track action points there is no posibility to change the title of the column. It could be useful

**Comment by drewhousman1010** [comment] 2021-03-26 14:45
A [user](https://app.hubspot.com/contacts/3888472/contact/22446251) 🔒 writes: 

> is it possible to add a new column in the dashboard?

**Comment by jordanh** [comment] 2021-05-07 00:01
We had +2 requests for this during this User Feedback Retro

**Comment by jordanh** [comment] 2021-05-07 00:02
Duplicate of #212

**Closed** 2021-05-07 00:03 UTC
Labels: design, discussion, enhancement
