### ISSUE TITLE
Mass-invitation link duration too short

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3954] opened 2020-06-24 23:17 UTC
This is a feedback thread to spool up user feedback relating to the duration our mass-invitation links are good for.

This thread will be closed when either we have consensus on a road forward and a link to a new issue, or that this thread has will be iceboxed due to 6 months of inactivity

**Comment by jordanh** [comment] 2020-06-24 23:17
[A user](https://app.hubspot.com/contacts/3888472/contact/11345501) writes 🔒 :
> Meeting link is only good for one day (when shared with others)

**Comment by jordanh** [comment] 2020-07-31 17:20
[A user (soon to be enterprise customer)](https://app.hubspot.com/contacts/3888472/contact/7270101) 🔒 writes:

> Most importantly, could you make it so the invitation link lasts longer than 24 hours? We ask folks to spool up feedback over a week or longer, and today I have to send out a new link each morning

**Comment by jordanh** [comment] 2020-07-31 17:21
[A user](https://app.hubspot.com/contacts/3888472/contact/10810851) 🔒  said:

> Could you make the invitation links last the duration of the sprint? Ours are 2 weeks

**Comment by jordanh** [comment] 2020-07-31 17:24
Today links are 13 characters in length.

@mattkrick out of curiosity, what napkin math do you use to calculate the trade offs between security and link length?

Alternatively posed, what would the link length be for:

* 7 days?
* 14 days?
* 21 days?
*28 days or a month?

**Comment by mattkrick** [comment] 2020-07-31 18:31
related issue: https://github.com/ParabolInc/parabol/issues/3359

the dictionary is 36 chars (A-Z0-9).
So 36 ^ 12 = 4.7E18 combinations
safe in terms of days isn't really relevant because the problem is human, e.g. who left their slack open/got pwned & now that attacker is cruising all the invitation links. the probability of a user getting pwned for bad security practices is far greater than a collision.

**Comment by jordanh** [comment] 2020-08-17 17:45
I've been thinking about this some and I wonder if this friction is really an opportunity.

First, let's talk about pwnage. The case we're trying to guard against is:

1. A user has a breach of information and/or leaks a mass-invitation link
2. A malicious user joins the team/org and gains access to company-sensitive information and/or opens a door for social-engineering attacks

Let's assume #1 happens, how might we reduce the risk for #2?

I think the key is to minimize the risk from "malicious users." Today, if is mass-invitation link is long-lived the risk is somewhat high on free accounts as when a link is accessed, a new user may join the team without email validation. I'd like to assume that a member validated as owning a user account with the same email domain is not malicious.

We could consider changing the mass-invitation user flow such that:

- If an account is attempting to join an org that...
   - ...has email verification enabled or SSO enabled _and,_
   - ...the email domain of the invited user matches the organization's email domain

- Then we allow invitation links to be valid for a longer duration (duration TBD) else we consider them expired after 24 hours
- If a user accesses an expired mass-invitation link, we tell them why it expires and how to make it last longer (i.e. pay $)
- In the future, these policies can be configured in org settings (along with SSO and email verification settings)

@mattkrick what do you think about this?

**Comment by mattkrick** [comment] 2020-08-18 17:42
if verification/SSO is enabled & the new person has a matching tld i think that's safe. the attack vector there is someone gaining access to an old company account (the Sony hack comes to mind) and using that to weasel in. I think I'm OK with that though.

> If a user accesses an expired mass-invitation link, we tell them why it expires and how to make it last longer (i.e. pay $)

i like this, but i'm not sure it's targeted at the right person. we're asking the invitee to ask the inviter to pay. "Hey Jordan, I know you just invited me to this crazy new product, but now it's telling me to ask you to pay." <-- that conversation probably won't happen. then again if we say something like "Ask Jordan to enable email verification" and don't mention the word upgrade, maybe it'll spark curiosity?

**Comment by jordanh** [comment] 2020-08-25 15:51
See also: #3994

**Comment by avivapinchas** [comment] 2020-08-25 16:15
In our persona research, we've heard from multiple users that starting a meeting is confusing. I believe they're looking to create a link to put into a calendar invite, and the confusion around how to do this is driving our softer-than-we'd-like activation numbers, which are the main thing we're currently focusing on. 

**With a view to making this easier and removing this critical point of friction, what can we do relatively quickly to make this safe-to-try?** I think we need to act on this within a matter of one or two sprints, because the data strongly suggests this is an important blocker. 

I'd propose: 
- Make the invitation link last longer for all users (maybe 1 week is still relatively safe?) 
- Change the copy on the button to something like 'Create a meeting', because 'start' suggests sync activity 
- Additional bits that would help: 
-- Let links for paid accounts stay active longer, and add a tool tip (or similar) for free users when creating the invite link that tells them the link expires in 1 week, and that they can pay for links that are active longer - I think that resolves the issue that @mattkrick pointed out on inviter vs invited 
-- For free accounts, when a link is expired, show the invitee one button that sends an automated email to the inviter to let them know - this would shorten the friction for invitees to notify inviters. The automated message would include an option to 'reactivate' the link. 

On the Growth side, we've [created documentation](https://www.notion.so/parabol/Starting-a-meeting-89f377304e4a4aacb572f6c343a78dd8) to address the issue, but as we all know, when you need docs to explain how the product works, you should probably just adjust the product. 

I respect that this points to larger UX issues we want to address long-term,  but right now, the evidence suggests this is what's actually eating our lunch.

**Comment by jordanh** [comment] 2020-08-25 16:18
Scheduling this discussion for resolution by adding it to the sprint board

**Comment by mattkrick** [comment] 2020-08-26 18:48
i think jordan's idea of extending the invitation life for people who share the same domain AND have verified email turned on is good. 
unfortunately, that will only benefit paid users, so i don't think it'll do much to address this tension.
if they don't read the "valid for 1 day" tooltip, they probably won't read the "upgrade to pro to extend the life" tooltip.

instead, i think we need to encourage people sending out a link direct to the meeting. not an invitation link.
if folks aren't a part of the team, it will send a snack notification to all online users to ask them to approve them to the team.

we could have a permalink that works in most cases e.g. `/team123/retro` and have that redirect them to the newest retro. 
however, i don't think that's the root tension, because they want folks on the team.
if given the choice between 1000 people having friction because they have to re-copy an invitation link vs. 1 person having an invitation link used against them & feeling like they got hacked, i'd take the 1000 every day.
products can recover from friction. if someone feels like they got hacked, even if it's their team member's fault, we'll never get them back.

**Comment by ackernaut** [comment] 2020-08-26 19:11
I think we decouple the concerns. An invite link needs to do just that and be as secure as possible. Having optionality when using the same domain and verified email is great.

If we have a platform for team activities we should make straightforward permalinks to those spaces once they’re created. We should reduce friction for them being created ahead of any intended sync time.

If somebody’s not a team member but has access to the link, they can knock and be let in. To keep things simple, they get added to the team. We can address the concerns of teams of teams, breakout groups, and/or guests later.

If folks create a recurring activity on the calendar, then we could have a factory object that stores settings and opens one new team activity at a time. Linking to the recurring item is forwarding them to the next open activity. With a recurring activity factory object, closing the latest activity it creates automatically opens the next instance.

**Comment by nickoferrall** [comment] 2020-08-27 12:09
I like the idea of making the team invite flow a bit smoother while nudging users towards the meeting invite link. The meeting link seems ideal for calendar invites and security but some users may want to join a team before a meeting has been created. 

I think we could make the team invite link flow a bit smoother by:

1. Implementing Jordan's idea of longer lifespan for same domain + verified email. It may only help paid users but that's still a positive. I imagine this would be a useful marketing tool too.
2. Adding a subtitle under "Share this link" mentioning the link duration and linking to the pro upgrade. This might be clearer than the tooltip and help reduce the number of nasty surprises.
3. Is a 1 day expiry the maximum period of time we're comfortable with?

And we could nudge users towards the meeting link by:

1. Creating a permalink for meetings
2. Queuing up team invite requests. It seems that the "X requests to join" snackbar pops up for online users but if the request happens when a user is offline, they don't see the request when the login? We could show users all outstanding requests to join team when they login and send them an email notification if someone hasn't been accepted after say 30 minutes.
3. Include invite to meeting link on "Invite to team" model, giving it centre stage above the team invite link
4. Could users awaiting permission to join the team still add anonymous reflections if they have the meeting link? The Group, Vote, Discuss phases all contain sensitive information but the user can only see what they've typed in the Reflect phase. Someone could take the link and write nasty things and perhaps companies would even want their Reflect titles to remain private, but this would let users add reflections before they're given access while protecting sensitive info.

**Comment by jordanh** [comment] 2020-08-28 18:18
@ackernaut wrote:
> If somebody’s not a team member but has access to the link, they can knock and be let in.

There are definitely 2 tensions here, and they are related. I think that's what makes deciding what to do difficult. There is certainly a "can my people get to the right place" that can be resolved via meeting permalink. I think we can create an issue for that and set it aside. Even if that tension were addressed, it wouldn't resolve the tension hit on by @nickoferrall where folks want to make sure people are invited to the team ahead of time. It's a, "can my people even get in the tool" kind of tension vs. "can my people get to the right place" kind of tension.

I want to focus on this "can my people even get in the tool" tension first as it appears earlier on the adoption funnel.

@nickoferrall's idea to queue up team invite requests is interesting, it puts more control in the hands of the team lead and creates a "knock, then enter" kind of protocol. I think it satisfies @mattkrick's, "Parabol is at reputation risk," security constraint. I think this ideas is worth litigating a bit further. Here's a drunken house set of AC:

* Mass invite links are valid for 1-day granting instant access
* Mass invitation links are further valid for 30 days since their create date, when clicked send "join requests" notifications to the Team lead
   * New users working through this flow must create an email and password
* Join requests sent via Notifications, which are batched via email (hopefully this still works!)
   * We could extend notifications to emit via Slack to make this even more seamless
* When join requests are accepted, the accepted invitee gets an email

Clarifications? Reactions to this?

**Comment by mattkrick** [comment] 2020-08-28 23:08
I have a strong opinion that we should not make the invitation logic more complicated. making a team lead dig through email or notifications is a step backwards (we used to do that, it was BAD)

i propose we add "1-day" and "30-day" expiration to the text in the invite modal and call it done.

if we need something more heavy handed, please add more user feedback (with full use cases!). without them, any implementation is just an expensive shot in the dark.

**Comment by jordanh** [comment] 2020-08-31 16:42
[A customer](https://app.hubspot.com/contacts/3888472/contact/1430601) 🔒 writes:

> Wanted to pass along this email from [redacted] on our team who has been running our retros on Parabol. She was trying to invite everyone to an async retro and the link she had expired every 24 hours so she started sending a daily email with a new link. It got tedious real fast. I told her that I was pretty sure that this wasn't how it was intended to work and asked for feedback on anything else she wanted to share. See below for her list. Feel free to reach out to Kristina if you'd like to ask her any questions.

[Verbatim from use](https://app.hubspot.com/contacts/3888472/contact/15192401)r:

> Maybe I've missed a few of these features:
>    * Invite link that doesn't timeout; 
> ...

**Comment by jordanh** [comment] 2020-08-31 16:44
Clarifying question @mattkrick:

Do you mean add text to clarify that mass invitation link expires after 1 day and invite by email expires after 30 days?

**Comment by mattkrick** [comment] 2020-08-31 17:17
yep! from these user comments i think it's clear that folks don't read the tooltip.

**Comment by jordanh** [comment] 2020-08-31 18:04
Opened #4123

I think this will address the "I'm surprised these links expired tension!"

What about instances where folks know that the link expires in 24 hours, but continue to send it daily anyway (as in [here](https://github.com/ParabolInc/parabol/issues/3954#issuecomment-683895164), [here](https://github.com/ParabolInc/parabol/issues/3954#issuecomment-667239866) or [here](https://github.com/ParabolInc/parabol/issues/3954#issuecomment-667239315))? Is our best path forward an an obvious meeting permalink? If so, could we capture a distinct design issue for that?

**Comment by mattkrick** [comment] 2020-09-01 01:01
if that's what they want to do, i think we need to understand why they don't just copy the meeting URL and share that. that will take existing parabol users to the meeting & for those just joining it will send a request to join to everyone else online.

**Comment by avivapinchas** [comment] 2020-09-01 16:39
My hypothesis would be: 
1. Getting the meeting URL requires starting a meeting, and we know folks feel uncertain about 'starting a meeting' before the actual meeting time. 
2. In the invite menu (ie what you can access by hitting '+' on either the team or meeting screens), we don't show that as an option. I'd assume all my invite options are under that '+' icon.

**Comment by mattkrick** [comment] 2020-09-01 17:10
1. This is probably true, although just going off the user comments above, it sounds like they already have a meeting open. if this isn't true, then we'll need more user feedback on folks who want this who don't have an open meeting

2. totally valid. i don't think there's a good way to mention this in the invite modal. telling someone to hop online & hope a team member is actively using the app feels bad. it means I'm dependent on someone else. it's a delightful surprise if it happens, but probably not a primary flow.

**Comment by jordanh** [comment] 2020-09-11 18:37
I met with [this new prospective user](https://app.hubspot.com/contacts/3888472/contact/2709) 🔒  who intends to use Parabol to run a workshop with a team at an organization they are working with. I recorded them speaking their thoughts as they were looking to set up a retro where people could join a meeting, offer their reflections ahead of time, and then finish sync. This user had never seen our interface. I took away a few key learnings:

   1. They expected Parabol to have "boards" with permalinks, each board should have its own URL and its own permissions
      * Starting a meeting to create a "board" was obvious enough
      * It wasn't clear the URL of the meeting could be shared with others
   1. The idea of a "team" controlling access to these "boards" was baffling
   1. It wasn't clear that the list of avatars on a meeting and the list of avatars on the team were the same list
   1. They were able to see, on their own, that mass-invitation links expired within 24 hours
   1. They were not able to see that email invitations would last for 30 days
   1. Inviting by mail from the team task dashboard worried them, "when people join this board, will they arrive here? how will they be able to find the 'board'?"

Ideas:
   * When we list team members in meetings, we add the team name near them (e.g. "Product team members") to make it more obvious where the list comes from
   * After implementing #4123, consider adding the ability for folks to add their own text to the invitation email – perhaps even a link to a meeting (perhaps we can make this flow easy?)
   * Similar to the above, if folks are sent an email invitation from a meeting context, include a link to the meeting and/or redirect them to the meeting automatically (vs. the task dashboard)
   * We add a design element to each meeting activity that allows them to copy the meeting permalink

What do we think of the above? Any other ideas to explore given the above feedback?

**Comment by nickoferrall** [comment] 2020-09-16 10:53
The Loom video was fascinating. I got the impression that he expected one simple way of inviting team members. The concept of a temporary team invite (link / email) and a sync meeting invite did feel confusing.

If we wanted to direct users to one simple way of inviting team members, what would it be? I'd say email invites. 

The 24hr team link is nice for Slack/Teams but the short window is inconvenient. Depending on online users for the sync meeting invite also isn't ideal. With email, the new 30 day window should work well for users, it's very common that you're invited to new apps via email and it's better from a security perspective.

With this in mind, I like Jordan's idea of letting users customise the invitation email. We could display a template email in the modal that includes instructional text about how to join the meeting. The template email would act as a "How to" guide that facilitators are more likely to read (reducing their anxiety).

The meeting permalink makes sense to me. I just tested the email invite and it looks like I was already redirected to an active meeting automatically?

Other thoughts:

- We could prioritise email invites by switching the order of the "Invite to Team" modal, i.e. "Send invites by email" at the top and "Or share this link" at the bottom (or remove the 24hr link concept altogether)
- Add "Invite to team" under "Add a Team" in the sidebar on the dashboard to give it more prominence
- We could add the small, green circle "active" icon to the avatars in the meeting. Perhaps that would help provide clarity that the avatar list in the meeting and team are the same?

**Comment by ackernaut** [comment] 2020-09-16 20:56
A few ideas here related to [the most recent round of user feedback](https://github.com/ParabolInc/parabol/issues/3954#issuecomment-691252024):
- I wonder (at least for certain tensions) if this user best represents our user base or is more of an outlier. We’ve designed Parabol to be very team-of-an-org-centric and have drifted from any notion of serving the **_consultant + change project_** user story. It’s natural for me to expect team-level access and collaboration with many software offerings opposed to the software being owned by a consultant who lets folks do a limited scope of change project activity on it. That’s more ‘just let me in and show me what to do’. Team-centric software is ‘I’m in the right place, what can I do here?’
- I think we should be explicit with the affordances:
  - **_Share the meeting link_** -> [copy meeting link]
    - **_Folks must be team members to join a meeting. Otherwise, if they arrive during the meeting, you can let them in._**
-- OR --
  - **_Invite new team members_**
    - **_Share this invite link. It’s valid for 24 hours._** -> [copy invite link]
    - **_Invite by email. Email invitations are valid for 30 days._** -> [add email addresses, send email with optional message]

I think it’d be great to know the context of the email invite. If from meeting XZY, add them to the team and send them there. If it’s sent from the team dash, just send them there. With improved IA 🤞 they’ll clearly see an open meeting to join.

I think if the meeting avatars are tapped, it could open the right sidebar where we show chat, video, and team/participant meta.

**Comment by avivapinchas** [comment] 2020-09-18 20:12
Just thinking in terms of shipping something faster if we decide not to prioritize bigger work here, and wanted to get an idea jotted down: could we look at the design of the invitation modal, and just basically add instructions for what someone should do?

It's not obvious to copy the URL of the meeting once you've created it, but that's a practice we want to recommend. It's also not obvious that inviting folks by email from within the meeting will take them straight into, which I think would be helpful to know and we could recommend explicitly. 

Doesn't solve the bigger problems, but maybe it resolves the 'what's the right way to do this?' confusion.

**Comment by jordanh** [comment] 2020-09-22 18:20
I'll scope a design exploration issue to resolve the "what's the right way to do this?" tension, I think that's well characterized

**Comment by ackernaut** [comment] 2020-09-23 21:03
Bad ideas:

What if in the context of a meeting we had [an explicit meeting link near the invite options](https://www.figma.com/file/G0dEQBKK9j5zGHDZsL3Lcp/Invite-Dialog?node-id=17%3A95)?

What if when folks hit a meeting link on a calendar item and weren’t on the team, [they could request access](https://www.figma.com/file/G0dEQBKK9j5zGHDZsL3Lcp/Invite-Dialog?node-id=21%3A307) regardless of whether somebody was at the meeting view to accept. The team lead or facilitator could get an email or Slack notification ‘Tap to allow name@company.co to join the MeetingName meeting and the TeamName team’

I don’t like the duality of the Meeting Link or Team Invite dialog. I think requesting access could be useful if folks end up finding a meeting link that was shared.

I think these are bad ideas because they’re trying to band-aid what we have today. There’s probably something we could do better with onboarding or optimistically opening meeting activities that would make it more obvious how and when to invite folks. I’ll keep simmering.

**Comment by pencerw** [comment] 2020-09-25 04:35
Excuse me chiming in here, but the 24 hour invitation link caused my team an issue.

I don’t have strong feelings on the security aspects here, but it seems like the “this link has expired!” page might also say “click here to request access from the team leader,” or at least prompt the user to create an account or something. Without those, the user has to email/Slack me directly and essentially complain that the link I sent them didn't work, which is a barrier to them joining my Parabol team. Having that approval process built in feels like it would alleviate that somewhat.

**Comment by ackernaut** [comment] 2020-09-29 17:30
Linking the things, we [had a conversation here](https://parabol.slack.com/archives/C836NA350/p1600907662014300) (internal) around invite link handing logic.

**Comment by ackernaut** [comment] 2020-09-30 18:20
I’m closing this discussion in favor of looking at a proposed enhancement #4224

**Closed by ackernaut** 2020-09-30 18:20 UTC
Labels: discussion

**Comment by shawneeatparabol** [comment] 2020-11-05 20:49
🔐 [Customer](https://app.hubspot.com/contacts/3888472/contact/19251301/) writes: 
"we have meetings, but someone always ask where the new meeting will be. Not very clear. the UI needs to help us understand. please stop designing to be "minimal" but instead be "focused and helpful"
