### ISSUE TITLE
Designed UX for handling accidental clearing of stories already estimated in a poker meeting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5006] opened 2021-06-01 17:14 UTC
The background is in #4992 

The short story is if folks have added an estimate to a story, then toggle the ‘select 50’ control it resets the issues in the meeting to have no points.

### Acceptance criteria
- [ ] Designed and proposed a UX flow that allows folks to update the list of stories without losing meaningful pointing estimation work already done in the same meeting. This can be validated with the team, and perhaps a the affected user or a few more

### Estimated effort
- 12 hours

**Comment by jordanh** [comment] 2021-06-22 18:15
Duplicate of #5060

**Closed by jordanh** 2021-06-22 18:15 UTC
Labels: design
