### ISSUE TITLE
Unable to push Story Points to Jira

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6589] opened 2022-05-19 15:35 UTC
During a Zoom call, one of [our customers](https://app.hubspot.com/live-messages/3888472/inbox/2239551345?globalSearchQuery=jared%40codecademy.com#email) shared that they can't push a Poker issue to Jira with the label Story Points.

To reproduce:

- Add a Jira issue to the Estimate phase
- Select the label Story Points 
- Press "Update"
- See a modal pop-up that says it's not configured but Parabol can do this for you
- Select "Fix it for me" and, after a delay, see the error message: `The request took too long`
- The same process happened when selecting "Original estimate". 

Note: in the user's Jira account, there was a lower & upper case spelling of both labels, e.g. "Original estimate" and "Original Estimate". We weren't able to find another label in the user's account that was only upper/lower case, so we couldn't test whether this is the issue.

### AC

- [ ] Can push an issue to Jira using the Story Points label
- [ ] Email [our customer](https://app.hubspot.com/live-messages/3888472/inbox/2239551345?globalSearchQuery=jared%40codecademy.com#email) to let them know that this functionality is now working

**Comment by treyparabol** [comment] 2022-05-19 18:53
A [user](https://app.hubspot.com/contacts/3888472/contact/73668751/) 🔒 wrote into Support:

> Is this a known issue where Jira doesn't update the story point estimate field? I've tried to troubleshoot but it doesn't work.

**Comment by treyparabol** [comment] 2022-05-24 06:25
A [user](https://app.hubspot.com/contacts/3888472/contact/78276401) 🔒  wrote into Support:

> After I completed the meeting, I noticed the story point weren't updated in JIRA. Is there a way to automatically send the updated story points into Jira?

**Comment by igorlesnenko** [comment] 2022-05-26 16:49
Here is what is going on:

* We fetch available fields and show them in dropdown. Custom field `Story points estimate` is also returned as available by Jira.
* However, initially it is not added to a particular project.
* So we suggest to fix that for user. And when user click "fix it for me" we are trying to add the field on a particular screen.
* However, it looks like something changed on Jira side (or always been like this?)
* It is not possible to add a field on screen for a simplified (team-managed) project anymore. 
* If we try to do that manually and open `Story points estimate` field configuration, we can see that there is no simplified projects screens available. We can see only company-managed projects screens here. See https://parabol-2.atlassian.net/secure/admin/AssociateFieldToScreens!default.jspa?fieldId=customfield_10016
* It looks like now the only way to manually add a custom field for simplified project is the following:
    * Open an issue
    * Click `Configure` 
    * Select `Number` field type
    * Enter `Story point estimate` name
    * Place it into Context section
    * Open the issue and see that the field is now displayed in the sidebar. Example: https://parabol-2.atlassian.net/jira/software/projects/IGORSIMPLE/boards/10?selectedIssue=IGORSIMPLE-4
    * Now go to poker meeting and see that you now able to update that field succesfuly

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/466991/170533312-26d17651-9272-4480-8bc6-d62948fee00b.png">

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/466991/170534088-d9e70bcb-d3ef-4b5b-9fa5-52e047295b06.png">


**Why do we see timeout error instead of any meaningful error?** 

We iterate a lot of projects and screens and do a lot of Jira API queries. In normal circumstances we quickly find the appropriate screen, fix the field, and do not iterate the rest. But here we keep iterating and it reaches the timeout.

**What I suggest:**

**1)** Verify that I found a correct root cause. To do this:

* Contact a customer and ask him what project type he uses. It is written in a sidebar of a kanban board and should be `team-managed`
<img width="853" alt="image" src="https://user-images.githubusercontent.com/466991/170531463-652e3143-0231-4d9b-9e84-61e54adec252.png">

* Ask him to manually add `Story point estimate` field using my instruction above. Add this to all issue types that he needs: `issue`, `bug` etc.

* Check with him if it fixed the issue and poker meeting works

**2)** If above is verified, close this issue, create a new issue to figure out how to best handle "fix field" functionality for simplified projects. Prioritize the new issue.

**Comment by igorlesnenko** [comment] 2022-05-26 17:09
Actually, we are trying to set some field for the issue here https://github.com/ParabolInc/parabol/blob/e1a99845a7f799b30d08f7a08412cf35e5c0afc6/packages/server/utils/ensureJiraDimensionField.ts#L70

Need to check why is it not working.

**Comment by igorlesnenko** [comment] 2022-05-26 20:33
My above solution was wrong. It is correct for any custom field, but for estimation the right way to fix the issue for simplified project is:

1) Go to Project Settings -> Features
2) Turn on the Estimation toggle.

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/466991/170575256-fd788270-320b-4725-8168-2c6b785b2852.png">

**Next steps**

1) Check if it is possible to fix automatically for simplified projects
2) Or show human-readable error instead of timeout

**Comment by igorlesnenko** [comment] 2022-05-26 20:46
Possible solutions to fix that in code

1)
In `addMissingJiraField` check if we are trying to update any estimation field for simplified project and show human-readable error about enabling estimation feature

2) Use rest API to enable that feature
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-project-features/#api-rest-api-2-project-projectidorkey-features-get

Probably need to request additional permissions

**Comment by igorlesnenko** [comment] 2022-05-27 09:17
For original estimate and remaining things are also different, we must drag time tracking field into the issue fields configuration. And our current `Fix it for me` approach does not work for that in simplified projects

**Comment by igorlesnenko** [comment] 2022-05-27 13:34
So root cause is figured out. 
Here are the 2 new issues.

* It looks like there is no automatic fix on our side for `Story point estimation` field. We need to just show a correct error: #6637 
* Original and remaining estimate could be theoretically fixed automatically, but still require above manual action: #6638

**Comment by mattkrick** [comment] 2022-05-31 15:52
great triage! sad to see that atlassian is actively breaking integrations without being backwards compatible.
one crazy thought-- i know we currently use legacy oauth2 scopes. if we use their new oauth2 scopes would it work?

**Comment by igorlesnenko** [comment] 2022-06-03 14:49
I found one more case that might cause the above issue #6675
And here is the fix: #6676

**Comment by drewhousman1010** [comment] 2022-08-29 18:28
A [user](https://app.hubspot.com/contacts/3888472/contact/87042201) 🔒 tried to implement Igor's instructions unsuccessfully. They said:

I gave these a shot and no joy. Same error.

It's worth noting that the permissions the integration asks for:

![unnamed](https://user-images.githubusercontent.com/80418360/187272253-5d330e4d-ba9c-440f-a575-d67cd7e4055f.png)

I don't have those by default.

I've tried creating the "jira-work" group, but it hasn't helped. But perhaps I did it wrong too.

I'll look into getting Igor access, I may have to spint up a sandbox project. I'll keep you posted.

**Comment by drewhousman1010** [comment] 2022-08-29 18:30
A [user](https://app.hubspot.com/contacts/3888472/contact/39601901) 🔒 said she can't update story points and does everything as comments.

**Comment by Dschoordsch** [comment] 2022-09-02 18:20
@drewhousman1010 

> I don't have those by default.

If the user does not have the permissions necessary to modify the Jira configuration to contain the voting fields, then they cannot authorize parabol to do it for them either.

**Comment by gcrickman** [comment] 2022-09-06 13:31
This [user](https://app.hubspot.com/contacts/3888472/company/8892830208) 🔒  said: 

> I was surprised that the 'final' story points I entered as the meeting organizer/faciltator were not automatically pushed to the 'story points' field we have on our issues in JIRA.

**Comment by nickoferrall** [comment] 2022-10-12 15:57
Update to this issue: @Dschoordsch is on the case and has created the following PRs to help resolve this:

- https://github.com/ParabolInc/parabol/pull/7257
- https://github.com/ParabolInc/parabol/pull/7258
- https://github.com/ParabolInc/parabol/pull/7264

@Dschoordsch if you could share a comment in this issue once we have news that we can update customers with, that'd be great 🙏

**Comment by Dschoordsch** [comment] 2022-10-12 16:03
The main difference is how we are reading the fields which we are able to edit from Jira. This should make a big difference, as this information is read issue specific instead of the project specific schema we've read before.
This might fix the issue in case a field was shown which isn't present in the edit issue screen or an unexpected field (e.g. "Story points" for a company managed project or "Story point estimates" for a team managed project) was used.

**Comment by enriquesanchez** [comment] 2022-10-12 18:00
A [user](https://app.hubspot.com/live-messages/3888472/inbox/3236045474#email) 🔒 wrote into Support:

>Hi Parabol team! I'm testing your tool to use it in the company that I work but I'm having a critical issue when updating the Story Points field on a Sprint Poker meeting. I'm able to give Jira Administrator permissions to Parabol but after that, I have an error saying: "Couldn't fix the missing field! In Jira, use "Find my field" to determine the error". I think the problem is that we are not using the default "Story points estimate" Jira field but a Custom one


The recommended steps for a workaround did not work for them:
```
1. Go to your Project settings
2. Go to Issues and then select the Screens tab in the sidebar
3. Click on the corresponding screen scheme in the issue type table
4. Find the Select Field dropdown and select the Story points field
```

**Comment by Dschoordsch** [comment] 2022-10-12 18:02
@enriquesanchez it is important to edit the edit screen (there are 3 screens, create, view and edit). They are correct if they're using "Story points" on a company managed project, we're filtering this out for some reason. I hope my fix will land next week.

**Comment by mwermuth** [comment] 2022-10-18 13:36
Thanks @nickoferrall and @Dschoordsch for the updates. Crossing my fingers that your PR's will fix a big part of this. I assume they are going out with the release tomorrow right?

**Comment by Dschoordsch** [comment] 2022-10-18 13:45
This should be retested after the next release which contains #7206.
The process of adding a field to be estimatable hasn't changed, but we
* improved the way we pick up available fields
* have a more polished description how to add the fields
  * https://www.parabol.co/support/estimation-in-jira-company/
  * https://www.parabol.co/support/estimation-in-jira-team/

**Comment by drewhousman1010** [comment] 2022-10-25 14:15
@Dschoordsch just asked 🤞

**Comment by mwermuth** [comment] 2022-11-04 14:02
@drewhousman1010 any news on this?

**Comment by drewhousman1010** [comment] 2022-11-07 16:52
@mwermuth not yet, I haven't heard back. I will nudge them again

**Comment by mwermuth** [comment] 2022-11-14 09:41
@Dschoordsch @drewhousman1010 if we don't hear back. Can we start to mark this done for now? I don't think there have been any other reports so far, and we did ship some improvements to this. How do you feel about that?

**Comment by nickoferrall** [comment] 2022-11-22 17:16
@mwermuth looks like @Dschoordsch and @drewhousman1010 agree with you. Happy for us to close this issue for now?

**Closed** 2022-11-29 17:18 UTC
Labels: bug, p1, Story Points: 13, Squad: 2

**Comment by drewhousman1010** [comment] 2022-12-01 13:42
Just ran into this issue with a [private managed instance customer. ](https://app.hubspot.com/contacts/3888472/company/7164993656)

They could only push points as comments. Maybe it's just a PPMI thing?

**Comment by drewhousman1010** [comment] 2022-12-14 18:18
A [user ](https://app.hubspot.com/contacts/3888472/contact/112452851) 🔒 writes: 

> Hi, when we try to sync story points on JIRA from Planning poker,  we cannot select "story points" field but comments. Any setting on Parabol or JIRA required ?
![screen_shot_2022-12-12_at_4 15 26_pm](https://user-images.githubusercontent.com/80418360/207675234-a7edeef5-aaef-4f2b-a018-052b6980dae6.png)

**Comment by Dschoordsch** [comment] 2022-12-14 19:39
Did they follow the instructions under the "Where's my field?" link?

**Comment by drewhousman1010** [comment] 2022-12-14 19:52
I asked them that and I will let you know what they say
