### ISSUE TITLE
JQL option "server error"

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4750] opened 2021-03-05 15:07 UTC
## Issue - Bug

A [user](https://app.hubspot.com/contacts/3888472/contact/13461101) 🔒 writes:

See [contact record for screenshots](https://app.hubspot.com/contacts/3888472/contact/13461101) 

> I tried to import stories from Jira, but it wouldn’t let me select the stories to view. I would get a “server error.
> Sometimes, I couldn’t get the JQL option to load
> 
> Once I did finally get the JQL option to load, I would try to select all the stories I want to display, the stories would get selected, and then they would automatically be DESELECTED and I would get this message
>

**Comment by jordanh** [comment] 2021-03-30 16:55
AC:
- Reproduced and triaged
- Bug resolved with PR or new issue created with new AC and EE

EE: 2 hours

**Comment by nickoferrall** [comment] 2021-04-09 16:09
Hey @gcrickman, I've just read through those emails and it looks like this is now fixed for the user? Should this issue be closed?

**Comment by jordanh** [comment] 2021-04-13 19:22
Confirmed this has been fixed

**Closed by jordanh** 2021-04-13 19:22 UTC
Labels: bug
