### ISSUE TITLE
Jira integration JQL queries issue: Unable to Select or Deselect all & selected item not match the Estimate items

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#6384] opened 2022-04-12 03:29 UTC
A [user](https://app.hubspot.com/contacts/3888472/contact/52938251) 🔒 is having trouble with JQL queries and sent along [a video](https://parabol.slack.com/archives/C4JAUUZ9P/p1649172574601499) to illustrate the problem.

> I hope it will help you to improve your product ;) 

This is supposed to be a bug that I was able to reproduce in my local environment, when there are too many query results for Jira integration, it is not possible to select or deselect all items, and the selected items do not match the Estimate items on the left.

[![20220412-Parabol Slack-001360@2x](https://user-images.githubusercontent.com/4997466/162874744-a790d31e-e405-4685-89e7-ba6ae11b44fe.png)](https://parabol.slack.com/archives/C4JAUUZ9P/p1649172574601499)

**Comment by JimmyLv** [comment] 2022-04-20 09:44
when scrolling down

**Comment by nickoferrall** [comment] 2022-05-12 06:32
Duplicate of https://github.com/ParabolInc/parabol/issues/6213

**Closed by nickoferrall** 2022-05-12 06:32 UTC
Labels: bug, p2, Story Points: 2
