### ISSUE TITLE
Story point Estimates fail to sync to Jira

### ISSUE THREAD

**Issue by hichamine** [ParabolInc/parabol#8489] opened 2023-07-07 10:56 UTC
A [user](https://app.hubspot.com/contacts/3888472/record/0-1/67989801) 🔒 mentioned that story points estimates fail to sync from sprint meetings to Jira, and that their team inputs estimates manually after each sprint poker.

**Comment by mwermuth** [comment] 2023-07-25 09:07
Came up during the backlog scrub. 

@Dschoordsch mentioned that you, @igorlesnenko looked into something related but the user didn't get back to you. Would you be up for taking a look?

**Comment by igorlesnenko** [comment] 2023-08-01 11:20
@hichamine I wasn't able find more details in the user profile on hubspot. Can you please give more details? Do they see any kind of error? What field are they using? Do you able to reproduce it?

@mwermuth I previously looked at similar issue, but was not able to find the root cause and reproduce. If you think it make sense to look into it again, I suggest to make it P2 and assign to the squad, as it is not something that we can figure out quickly.

**Closed** 2024-01-30 10:27 UTC
Labels: bug, icebox, p3, Squad - Self Raising
