### ISSUE TITLE
Personalized In-App prompts from Parabol to end-users

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4011] opened 2020-07-22 19:28 UTC
I'm having issues where some key contacts I'm reaching out to don't open my emails and are unreachable over the phone. In these cases I don't know if I'm getting stuck behind a spam filter or just being ignored. If we could engage users directly through the platform in these situations, that would be ideal. 

If a 2-way chat window could pop up the next time they're online, with a custom drafted message from us requesting a response & possibly having a CTA to book a call, that would quickly address this issue.

**Comment by ackernaut** [comment] 2020-07-22 20:02
‘Want to remove this chat window? Upgrade to Pro’ 😆

**Comment by shawneeatparabol** [comment] 2020-07-28 23:07
More like 'Hi Terry, Thanks for using Parabol! I'm your account manager and I've been trying to reach you with important information regarding your account but haven't been able to get through. Do we have your email right: XXX@company.com?" And then we either get a response or we know for a fact that they're just ignoring us. Similar to the payment prompt.

**Comment by shawneeatparabol** [comment] 2020-07-28 23:10
Right now having the issue with🔐 [this prospect](https://app.hubspot.com/contacts/3888472/contact/12076201)and🔐 [this prospect](https://app.hubspot.com/contacts/3888472/contact/11839301) both at enterprise consultancy accounts

**Comment by jordanh** [comment] 2020-12-08 19:36
Duplicate of #3792 

Closing

**Closed by jordanh** 2020-12-08 19:36 UTC
Labels: discussion
