### ISSUE TITLE
fix fatal error with rtc

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3638] opened 2020-03-09 19:32 UTC
https://sentry.io/organizations/parabol/discover/action-production:6e9100c94c7d473782d2fc8aec065809/?field=title&field=event.type&field=project&field=user&field=timestamp&name=All+Events&project=107196&query=&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1

AC
- [ ] triaged and new issue opened or fixed

EE
- 10.5

**Comment by jordanh** [comment] 2020-03-24 17:14
Duplicate of #3200, closing

**Closed by jordanh** 2020-03-24 17:14 UTC
Labels: bug
