### ISSUE TITLE
UI Bug: Large team member list

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#4721] opened 2021-02-26 09:57 UTC
## Issue - Bug

- When a team member list exceeds a certain count, Settings & Integration div converts to scroll. CSS overflow is currently set to auto for this div.
- When a team member list exceeds a certain count, UI overlapping occurs. This UI overlap seems to occur when width is above 1816 pixels.
- When a team member list exceeds a certain count, entire page must be scrolled to see complete list

![image](https://user-images.githubusercontent.com/71724289/109285265-7b50ac00-77e6-11eb-921e-21f7ee1373c0.png)

**Comment by jordanh** [comment] 2021-03-16 18:29
Duplicate of #4566

**Closed by jordanh** 2021-03-16 18:29 UTC
Labels: bug
