### ISSUE TITLE
Org admin enhancements designed

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5112] opened 2021-07-07 23:29 UTC
A [user](https://app.hubspot.com/contacts/3888472/contact/28003151) 🔒 says:

> On an organization level, I can’t elect somebody a super admin to see everything

**Comment by avivapinchas** [comment] 2021-07-08 01:44
The needs I specifically heard in the clip here were: 
- We want to be able to add and remove folks from teams, without the team leads having to do that all the time
- We like that 'management' doesn't have access to retro and meeting info - so this role should have user access permissions, but not be 'on the team' necessarily

**Comment by jordanh** [comment] 2021-07-10 23:29
## AC

A design that:
   - [ ] Allows for a new role named "Admin" to be assigned to Org Users

When the "Admin" role is assigned:

   - [ ] Can see which teams are subordinate to an Organization
   - [ ] Can manage team membership of the teams
   - [ ] *Cannot* see task or meeting summary data
   - [ ] May see enagement statistics (e.g. number of meetings ran, last meeting ran)

**Comment by jordanh** [comment] 2021-08-08 23:04
Marking as duplicate of #4407

**Closed** 2021-08-08 23:04 UTC
Labels: enhancement, design
