### ISSUE TITLE
Large retro crash

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4734] opened 2021-03-03 21:43 UTC
## Issue - Bug

A [user](https://app.hubspot.com/contacts/3888472/contact/10617801) 🔒 writes:

> Service Crashed during Large Retro
> Message: I wanted to provide feedback that during a large retro, 60+ people, on March 2nd at 2pm EST we noticed the application crashed and on a refresh could not be reloaded.

AC
- [ ] root caused triaged, fixed or new issue(s) opened

EE 
- 1 hour

**Comment by tiffanyhan** [comment] 2021-03-04 19:02
https://sentry.io/organizations/parabol/issues/?project=107196&query=is%3Aunresolved+event.timestamp%3A%3E%3D2021-03-02T19%3A00%3A00.000Z+event.timestamp%3A%3C2021-03-02T20%3A00%3A00.000Z&statsPeriod=14d

Looks like they hit a redis timeout

https://sentry.io/organizations/parabol/issues/1666567181/tags/user/?project=107196&query=is%3Aunresolved+event.timestamp%3A%3E%3D2021-03-02T19%3A00%3A00.000Z+event.timestamp%3A%3C2021-03-02T20%3A00%3A00.000Z&statsPeriod=14d

**Comment by tiffanyhan** [comment] 2021-03-04 19:42
seems to correspond with a spike in redis commands per sec at around ~11:30am pst

https://app.datadoghq.com/screen/integration/15/redis---overview?from_ts=1614700800000&live=false&to_ts=1614715200000

**Comment by tiffanyhan** [comment] 2021-03-04 19:51
what retry mechanisms do we have in place in the event of redis timeout? what is the minimum worker threads config set to in prod?

**Comment by jordanh** [comment] 2021-05-03 23:50
I think this was caused by insufficiently sized pg connection pool. Closing for now

**Closed by jordanh** 2021-05-03 23:50 UTC
Labels: bug
