### ISSUE TITLE
GitLab: adding many issues to the scope breaks poker meeting

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6386] opened 2022-04-12 08:56 UTC
## Issue - Bug

- Create a poker meeting
- Connect GitLab
- Add 20 issues to the poker scope (You can do it manually as `select all` is broken right now #6213)
- Refresh the page
- See all the issues in the sidebar are now displayed as "Task imported from GitLab"
- See the error in server logs: `Query has complexity of 330, which exceeds max complexity of 250`
- Try to select any project in a filter
- See the app crashes

![image](https://user-images.githubusercontent.com/466991/162922144-123f3da0-2a2e-40d2-be17-92294e969e83.png)

### Acceptance Criteria (optional)
- [ ] It should be possible to add 20+ issues to poker scope

**Estimated effort:** 4h

**Comment by nickoferrall** [comment] 2022-05-12 09:14
https://github.com/ParabolInc/parabol/issues/6540 is technically a duplicate of this issue but as https://github.com/ParabolInc/parabol/issues/6540 is linked to a PR, I'll close this issue

**Closed by nickoferrall** 2022-05-12 09:14 UTC
Labels: bug, p2, 🥇goal, Squad: 1
