### ISSUE TITLE
Locking enhanced to be at User level, not Team level

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#6378] opened 2022-04-10 17:27 UTC
Sales are observing the phenomenon that users are bypassing our org-level over-limit locking in significant numbers. Users are creating new org/team combinations to continue running meetings. Flattering for sure, but this makes forcing a conversation difficult.

This issue exists to explore an alternative locking strategy, in which we can lock out users at the user level _in addition_ to the org level.

### Acceptance Criteria (optional)
An architectural design, written as a GitHub issue that:
   - Allows sales to run a single mutation that would continue to lock an org
   - Enhances our Hubspot integration to set a new Hubspot property indicating that user is locked out
   - Also lock users at the user level to prevent them from starting additional meetings, even if they make additional orgs
      - can they still create an org?
      - do we display the lockout message on any new teams they create?
   - An exploration of alternative ideas that may come to mind

**Estimated effort:** Up to 8 hours to explore and write.

**Comment by nickoferrall** [comment] 2022-07-13 10:59
Here are a few possible approaches:

### 1. Update `lockTeams` to lock all users within a team by default

The `lockTeams` mutation could include an optional `lockUserIds` arg. If null/undefined, it would lock all users within the team. If the array includes user ids, only those ids are locked. If the array is empty, no users are locked. 

We would add `isLocked` to the User object. Locked users wouldn't be able to create a new team/org, but could create a meeting.

If the `lockTeams` arg `isPaid` is true, it would unlock all users.

Pros:

- We wouldn't need to create a new mutation

Cons:

- It's unclear that `lockTeams` would also lock users so it might need to be renamed to `lockTeamsAndUsers`, which feel spaghetti-y
- It could be expensive to update all of the users in an org
- We wouldn't be able to lock specific users
- Users that have already dodged the rules and created a new team/org wouldn't be affected 

### 2. Create `lockUsers` and `unlockUsers` mutations

Create two new mutations: 
- `lockUsers(teamIds: string[] | null, userIds: string[] | null, lockMeetings: boolean)`. 
- `unlockUsers(teamIds: string[] | null, userIds: string[] | null)`

Add `isLocked` and `isMeetingsLocked` to the User object. 

In `lockUsers`, if `teamIds` are specified, all users within those teams are locked. If `userIds` are specified, it only locks those users. If `lockMeetings` is false, only `isLocked` is updated, which prevents users from creating new teams/orgs. If `lockMeetings` is true, those users can't create new meetings either.

We could implement one mutation instead of two called `toggleLockUsers`, which would toggle `isLocked`. However, if we locked a user with `lockMeetings: false` and then wanted to change this to `true`, the logic begins to get tangled. Instead, I think it's cleaner to have two mutations.

Generally, I think we should lock all users within teams rather than specific users. Otherwise, a user can ask a colleague to create a new team/org.

Pros:

- Flexible - can lock specific users, entire teams, and lock meetings
- Can easily unlock users once they've paid 
- Helps with current negotiations as we could prevent teams that have dodged the `lockTeams` restrictions from creating meetings

Cons:

- Requires two new mutations

### 3. Prevent users from creating new orgs/teams if one of their teams are locked

When creating a new team/org, we'd check if the user belongs to any locked teams. If they are, show the locked modal. 

Using the same logic, we would prevent users from deleting the team/org or from leaving it. This would prevent users from deleting a team/org to dodge the restriction.

If we wanted to be stricter, we could prevent users that belong to a locked team from creating new meetings too.

Pros:

- We wouldn't need to create/update any mutations
- Locking a team is cheaper than updating all/many User objects

Cons:

- It wouldn't solve the issue for current negotiations where someone has already created a new org/team
- We wouldn't be updating the User object so we wouldn't add a Hubspot property for each user
- Users that belong to one org that has paid and another that hasn't may feel frustrated that they can't create a new org/team
- The mutations to start a meeting, leave a team/org, and delete a team/org would be more expensive as we'd need to check all of the viewer's teams
- We wouldn't have the flexibility to prevent some users who belong to a locked team from creating a meeting while allowing others

-----

I suggest option 2 because it gives the sales team the most options during negotiations. They can lock entire teams or specific users, they can prevent them from creating meetings, and also unlock them. 

@mattkrick it'd be great to get your thoughts!

**Comment by mattkrick** [comment] 2022-07-15 18:03
I really like option 2! My .02:
- i like allowing team creation & preventing meetings-- a single injection point is simpler
- like you say, attaching a flag to a user isn't perfect, especially because someone could create a new user, start a new team, invite everyone & then leave the meeting
- we don't want to keep people from leaving a team/org, that could get complex. thankfully, that's why we keep `removedAt` or `isNotRemoved` flags on those objects, although if folks are leaving old teams & starting new ones to get around the ban, I'm almost inclined to let them have it

I think we could keep this really simple & only need to edit a single file: https://github.com/ParabolInc/parabol/blob/5c97d33947be89855eb9bd6c92641eee0d2ee1b9/packages/server/graphql/mutations/helpers/isStartMeetingLocked.ts. I can't articulate it well with words, so I just wrote some untested code. For your consideration:

```ts
const isStartMeetingLocked = async (teamId: string, dataLoader: DataLoaderWorker) => {
  const team = await dataLoader.get('teams').loadNonNull(teamId)
  const {isPaid, lockMessageHTML, tier} = team
  if (tier !== 'personal') {
    return isPaid ? null : 'Sorry! We are unable to start your meeting because your team has an overdue payment'
  }
  // if this team was manually locked, be mean because they called this by hiding the modal
  if (lockMessageHTML) return 'Wow, you’re determined to use Parabol! That’s awesome! Do you want to keep sneaking over the gate, or walk through the door with our Sales team?'
  // if this team wasn't manually locked, see if any of its members are on locked teams
  const teamMembers = await dataLoader.get('teamMembersByTeamId').load(teamId)
  const userIds = teamMembers.map(({userId}) => userId)
  const allTeamMembers = (await dataLoader.get('teamMembersByUserId').loadMany(userIds)).filter(isValid).flat()
  const teamIds = [...new Set(allTeamMembers.map(({teamId}) => teamId))]
  const allRelatedTeams = (await dataLoader.get('teams').loadMany(teamIds)).filter(isValid)
  const anyTeamIsLocked = allRelatedTeams.some((team) => team.lockMessageHTML)
  return anyTeamIsLocked ? 'One or more of your team members is over the usage limit'. Please contact sales : null
}
```

**Comment by nickoferrall** [comment] 2022-07-19 15:33
I like it! It's similar to option 3, but it prevents new meetings instead of preventing users from creating new orgs/teams. 

If users are currently creating a new team & inviting everyone there, it seems fairly likely that they would also delete their old team to get around this new restriction. But I think we can start here and increase the severity of the restrictions if users keep dodging them. 

I'll create an issue to go with this approach initially and, if people just delete their teams, we could look at implementing option 2.

One question: do you think it'd be best to let the user know which team(s) is over the usage limit? I don't think so - it'd be better from a UX standpoint as they could go to that org and pay, but it'd also make it more likely that they would delete the mischievous team.

**Comment by nickoferrall** [comment] 2022-07-19 17:28
Closing this issue now https://github.com/ParabolInc/parabol/issues/6897 has been created

**Closed by nickoferrall** 2022-07-19 17:28 UTC
Labels: enhancement, architecture, Squad: 3

**Comment by avivapinchas** [comment] 2022-07-20 17:28
Saw this, so just chiming in to answer your Qs. Leaving it here even though the issue is closed, cuz this is where the questions are. 

> Do you think it'd be best to let the user know which team(s) is over the usage limit? I don't think so - it'd be better from a UX standpoint as they could go to that org and pay, but it'd also make it more likely that they would delete the mischievous team.

I agree with you. For the current lock modal, we specify a message - I would imagine that same message shows here as well. 

> Why do we lock by team instead of org if org is the paying entity?

A few things can happen: 
- A team lead may choose to pay for their own teams, but then others within the org need to be locked out
- A company may say 'oh we'll just fit into the free tier' - then we'll lock all but 2 teams, since they can have 2 teams on the free tier

🤔 I suppose we could move teams to diff orgs to accomplish these? But that's not what we do in practice today, afaik

**Comment by nickoferrall** [comment] 2022-07-21 10:20
Thanks for answering the questions!

> A company may say 'oh we'll just fit into the free tier' - then we'll lock all but 2 teams, since they can have 2 teams on the free tier

Ahh that makes sense! Looks like we should stick with locking by team then 👍
