### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getLinkedRecord')

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8141] opened 2023-05-03 13:43 UTC
https://parabol.sentry.io/issues/4131697142/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'getLinkedRecord')
  at acceptTeamInvitationNotificationUpdater (./packages/client/mutations/AcceptTeamInvitationMutation.ts:110:24)
  at value (./packages/client/subscriptions/subscriptionUpdater.ts:1:440)
  at fn (./packages/client/subscriptions/subscriptionUpdater.ts:17:51)
  at _optionalChain (./packages/client/subscriptions/subscriptionUpdater.ts:1:418)
  at updater (./packages/client/subscriptions/subscriptionUpdater.ts:17:5)
...
(33 additional frame(s) were not displayed)
```

9 events 8 users

**Comment by jmtaber129** [comment] 2023-05-03 13:58
@igorlesnenko this seems like a duplicate of https://github.com/ParabolInc/parabol/issues/8090. Not sure why sentry has two separate issues for these.

**Comment by jordanh** [comment] 2023-05-12 15:41
Closing as duplicate

**Closed by jordanh** 2023-05-12 15:41 UTC
