### ISSUE TITLE
Content flashes when opening new meeting modal

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6943] opened 2022-07-26 13:48 UTC
## Issue - Bug

When a new meeting modal is opened for the first time, the whole content flashes. see the video below.
https://user-images.githubusercontent.com/1017620/181021549-d53a042d-83b3-4fb7-bc73-43338d155b38.mp4

It only happens once, when you open a modal for the second time (without refreshing the page), the flash won't happen.

### Acceptance Criteria (optional)
- [ ] content does not flash when opening new meeting modal

**Comment by Dschoordsch** [comment] 2022-07-28 06:49
The flickering is caused by this `Suspense`: https://github.com/ParabolInc/parabol/blob/0913e5ba2c2b643099c60cd18f9c83194e2afa0b/packages/client/components/DashboardRoot.tsx#L18
It briefly goes into the suspense mode before rendering the dashboard again

**Comment by BartoszJarocki** [comment] 2022-07-28 10:27
How can we prevent triggering suspense at the dashboard level? I'd assume it'd trigger the suspense but on the `NewMeetingRoot` level 🤔

**Comment by Dschoordsch** [comment] 2022-07-29 15:20
I would have guessed the same, but replacing its content with `null` still shows the same flashing and `DashboardRoot` is what gets re-rendered and the Suspense fallback is rendered as well.

**Comment by BartoszJarocki** [comment] 2022-07-29 15:24
then, there's a mystery to solve! 🕵️‍♂️

**Comment by Dschoordsch** [comment] 2022-07-29 17:20
Unassigned myself in case someone wants to take a look while I'm away. I suppose this needs some debugging in Suspense. There is some work done on Suspense in react 18, but simply updating it and relay did not solve the problem for me.

**Comment by jordanh** [comment] 2023-02-28 19:57
Will be fixed by "Activity Library"

**Closed by jordanh** 2023-02-28 19:57 UTC
Labels: bug, icebox, p4
