### ISSUE TITLE
Can't push tasks to Jira without adding description field 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#8404] opened 2023-06-20 17:03 UTC
An [enterprise customer ](https://app.hubspot.com/contacts/3888472/contact/88953451) 🔒 wrote in saying they cannot push tasks to Jira without adding a description field. Their problem is shown in the attached gif. 

![parabol to jira](https://github.com/ParabolInc/parabol/assets/80418360/ecae2dbf-92b0-4d90-a841-03e0ce6face5)

**Comment by jordanh** [comment] 2023-06-20 17:08
@nickoferrall I agree with what [you said in Slack](https://parabol.slack.com/archives/C4JAUUZ9P/p1687280009872099?thread_ts=1687275731.522389&cid=C4JAUUZ9P), this is a p2 so I marked it as such and assigned it to your squad

**Comment by nickoferrall** [comment] 2023-07-03 18:12
I've tested this locally with a team on the Enterprise tier (and another on the Starter tier), but I couldn't reproduce it. Will come back to this with a fresh mind and dig into it further. 

If there's any update from the customer @drewhousman1010, please let me know 🙏

**Comment by drewhousman1010** [comment] 2023-07-05 14:46
@nickoferrall an update from the user:

> I wanted to let you know that this may not have been an issue with your app, but more user error on our side.
> 
> We found that on the Parabol card we need to enter test on one line and then hold shift and hit enter and then add test to a second line and that would make it work.
> 
> The second line of the Parabol car ends up going to the Description field in our Jira instance.
> 
> thanks

**Comment by nickoferrall** [comment] 2023-07-06 09:23
Thanks for the update, @drewhousman1010. 

I'm not sure what they mean - a gif would be very helpful, although I appreciate it can be difficult to ask for this now that they no longer have the problem. 

The gif that they originally shared should work, so if that's still not working, we should fix it.

Still, if we haven't had any other customers mention this, and this customer says that it's not an error on our side, I think it's safe to close this issue. Feel free to reopen if you disagree!

**Closed by nickoferrall** 2023-07-06 09:23 UTC
Labels: bug, p2, Squad - Self Serve
