### ISSUE TITLE
Add source map to Datadog RUM

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6731] opened 2022-06-13 15:46 UTC
Relates to:
* #6071

Right now error tracking only shows errors in the minified .js files. To evaluate whether or not we will have the same information available, we need to upload the source map
Datadog:
![Screenshot from 2022-08-19 10-41-53](https://user-images.githubusercontent.com/7331043/185580911-ab284e0d-75f6-4cec-ae79-dcd1109abbf8.png)
Sentry:
![Screenshot from 2022-08-19 10-42-00](https://user-images.githubusercontent.com/7331043/185580923-119a4267-1a1b-458d-86b7-e6abe25b3a24.png)

## Acceptance criteria
* [ ] Deploying to production automatically pushes the correct source map with correct metadata (version/path)

**Comment by mattkrick** [comment] 2022-06-17 19:22
that error comes from react itself.
in development, react uses a different version of itself full of helpful error messages. in prod, it removes all of those. well still get a stack trace, but we'll have to reproduce it in development. 
_usually_ this is caused by a missing `key` on an element, or a component is unmounted before it is cleaned up.

**Comment by mattkrick** [comment] 2022-07-26 18:37
closing as the fix won't fix the error

**Comment by Dschoordsch** [comment] 2022-08-19 08:45
Although the mentioned error would not have been fixed, we're still missing the source map for nice stack traces.

**Closed** 2022-08-25 16:06 UTC
Labels: enhancement, Story Points: 3, Story Points: 5, Next Sprint: Y, Squad: 3
