### ISSUE TITLE
Cannot find module './generated/getUsersByIdsQuery'

### ISSUE THREAD

**Issue by kemalgoekhan** [ParabolInc/parabol#7912] opened 2023-03-13 10:15 UTC
I use existing dockerfile on repo for self hosted parabol with this command 

`docker-compose -f docker-compose.yml -f ./docker/docker-compose.selfHosted.yml up -d`

on  `https://github.com/ParabolInc/parabol/blob/master/docker/Dockerfile.prod` which has [Node 18](node:18.14.2). 

at `yarn build` step it gives error. my environment file is as mostly localhost like example file except host variable. What is the reason for this? anyhelp, appreciated. 

```
webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:4
#0 34.12 var _getUsersByIdsQuery = __webpack_require__(Object(function webpackMissingModule() { var e = new Error("Cannot find module './generated/getUsersByIdsQuery'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
#0 34.12                                                                                                ^
#0 34.12
#0 34.12 Error: Cannot find module './generated/getUsersByIdsQuery'
#0 34.12     at webpackMissingModule (webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:4:96)
#0 34.12     at eval (webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:4:201)
#0 34.12     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:176:1)
#0 34.12     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10189:41)
#0 34.12     at eval (webpack://parabol-action/./packages/server/utils/segmentIo.ts?:2:22)
#0 34.12     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:431:1)
#0 34.12     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10189:41)
#0 34.12     at eval (webpack://parabol-action/./packages/server/graphql/mutations/addAgendaItem.ts?:9:18)
#0 34.12     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:298:1)
#0 34.12     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10189:41)
#0 34.12     at eval (webpack://parabol-action/./packages/server/graphql/rootMutation.ts?:2:22)
#0 34.12     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:291:1)
#0 34.12     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10189:41)
#0 34.12     at eval (webpack://parabol-action/./packages/server/graphql/public/rootSchema.ts?:17:21)
#0 34.12     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:242:1)
#0 34.12     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10189:41)
#0 34.12     at eval (webpack://parabol-action/./packages/server/graphql/private/rootSchema.ts?:3:19)
#0 34.12     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:207:1)
#0 34.12     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10189:41)
#0 34.12     at eval (webpack://parabol-action/./packages/server/utils/updateGQLSchema.ts?:11:19)
#0 34.12     at Array.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:193:1)
#0 34.12     at __webpack_require__ (/parabol/scripts/toolbox/updateSchema.js:10189:41)
#0 34.12     at /parabol/scripts/toolbox/updateSchema.js:10242:37
#0 34.12     at Object.<anonymous> (/parabol/scripts/toolbox/updateSchema.js:10247:12)
#0 34.12     at Module._compile (node:internal/modules/cjs/loader:1254:14)
#0 34.12     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
#0 34.12     at Module.load (node:internal/modules/cjs/loader:1117:32)
#0 34.12     at Module._load (node:internal/modules/cjs/loader:958:12)
#0 34.12     at Module.require (node:internal/modules/cjs/loader:1141:19)
#0 34.12     at require (node:internal/modules/cjs/helpers:110:18)
#0 34.12     at updateGraphQLSchema (/parabol/scripts/runSchemaUpdater.js:29:10)
#0 34.12     at runSchemaUpdater (/parabol/scripts/runSchemaUpdater.js:34:10)
#0 34.12     at async generateGraphQLArtifacts (/parabol/scripts/generateGraphQLArtifacts.js:7:3)
#0 34.12     at async prod (/parabol/scripts/prod.js:25:3) {
#0 34.12   code: 'MODULE_NOT_FOUND'
#0 34.12 }
```

**Comment by mray190** [comment] 2023-03-22 01:52
Same issue. Default instructions, nothing changed

**Comment by tianrunhe** [comment] 2023-03-27 11:26
Hi, could you try `yarn pg:build` and then `yarn dev`?

**Comment by kemalgoekhan** [comment] 2023-04-03 06:15
> Hi, could you try `yarn pg:build` before `yarn dev`?

https://github.com/ParabolInc/parabol/blob/master/docker/Dockerfile.prod
Thanks for reply @tianrunhe 
There is a step yarn build before yarn install --prod --frozen-lockfile. 

Should I use this prod dockerfile?

**Comment by jordanh** [comment] 2023-04-11 17:17
@kemalgoekhan curious to ask you if you are still running into this?

You shouldn't need to run the production Dockerfile just to get our app up for testing.

**Comment by kemalgoekhan** [comment] 2023-04-12 06:30
@jordanh 
Yes, the problem is still ongoing. Since the project is open source, I thought that the paid part would be the part that you provide as a cloud service as SaaS, and I could use the free version by installing it on my own host. Do you have such support?

**Comment by Dschoordsch** [comment] 2023-04-12 08:33
@kemalgoekhan that is possible, but not well documented as it's currently changing quite a lot for us as well. Especially building a docker image and running the app from it is work in progress.

If you're not settled on running docker, you could use dokku and follow our process here: https://github.com/ParabolInc/parabol/blob/master/.circleci/config.yml

If you're set on using docker, you should start by looking here: https://github.com/ParabolInc/parabol/tree/master/docker/parabol-ubi/docker-build

**Comment by kemalgoekhan** [comment] 2023-04-13 10:16
@Dschoordsch hey, thank you for information. I deployed as you said. still there is a small problem. it cant save my reflects.

https://im5.ezgif.com/tmp/ezgif-5-5969388b5e.gif

**Comment by Dschoordsch** [comment] 2023-04-13 11:10
@kemalgoekhan that sounds like a different problem. The server log should have more information. If the problem is not clear from the logs, please open a different issue. I will close this one as you've got it running.

**Closed by Dschoordsch** 2023-04-13 11:10 UTC
Labels: bug, p3, Question
