### ISSUE TITLE
Unable to export csv file for a single meeting

### ISSUE THREAD

**Issue by treyparabol** [ParabolInc/parabol#5248] opened 2021-08-04 20:43 UTC
A [user](https://app.hubspot.com/contacts/3888472/contact/39183551/) 🔒  writes:

> We just completed a meeting and have all of the reflection content and grouping that we wish to export to CSV file -- we see the button/text saying download, but no CSV file is produced... Can you please help us?

Background: They are able to export CSVs for all other meetings with the exception of the one below:
![githubbug](https://user-images.githubusercontent.com/88459947/128251633-ddf92438-6459-4fe3-8aeb-d0c1d646f188.png)

Additional context: 

> FYI - We also had problems during the session with all of our attendees – Natalie moved the meeting to vote and everyone was getting errors and could not vote, and then to try and keep our meeting going she moved the meeting to Discuss (we had to move to discussion as everyone was stuck.)  when she moved it to Discuss none of us could see it in the same phase, we were all still seeing the Group phase…  That was when we decided to end the meeting since we could not use the tool for team members to enter actions etc…

**Comment by jordanh** [comment] 2021-08-05 03:01
I found no related sentry issues for the user id. Will investigate further...

**Comment by jordanh** [comment] 2021-08-05 03:38
I debugged this a bit, here's what I found.

When accessing this URL: https://action.parabol.co/new-summary/5cVMwQLims/csv

The graphql query is returning `[]` stages for the discuss phase of the meeting.

https://github.com/ParabolInc/parabol/blob/6a0bba7dc6e6fb42163dedb8783b34418a599709/packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx#L183

Why? Because the meeting was terminated at the Group phase. There is no discuss phase. The CSV export currently requires that our meeting has completed all phases.

**Comment by jordanh** [comment] 2021-08-05 04:39
## Acceptance Criteria
- "Robustify" ExportToCSV.tsx's retrospective row generator to handle cases where we only have data up until:
  - the reflect phase
  - the group phase
  - the vote phase
- Optional: hide the ExportToCSV button if the meeting was terminated without any reflections

## Estimated Effort
- 12 hours

**Comment by jordanh** [comment] 2021-08-05 11:23
Spoke to @BartoszJarocki. Duplicate of #5191 and #5244. Closing in favor of these.

**Closed by jordanh** 2021-08-05 11:23 UTC
Labels: bug, p1
