### ISSUE TITLE
timer not adding time in proper increments 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5413] opened 2021-09-17 16:40 UTC
A [user](https://app.hubspot.com/contacts/3888472/contact/18965751) 🔒  writes:

> **Observed Behavior:**
> *When* I am logged in and facilitating a meeting in Parabol
> *And* I try to set a one or two minute timer for a section/topic
> *Then* no timer is set on the section/topic
> 
> **Expected Behavior:**
> *When* I am logged in and facilitating a meeting in Parabol
> *And* I try to set a one or two minute timer for a section/topic
> *Then* a timer of the selected duration is added and starts counting down
> 
> The same behavior is seen when extending time on an existing timer.
> 
> Perhaps there’s an issue between local system time and the system time on one of the servers (NTP mismatch)?

[Hubspot ticket](https://app.hubspot.com/contacts/3888472/ticket/566383492) 🔒

**Comment by mattkrick** [comment] 2021-09-21 18:05
Next steps:
- try to reproduce locally
- try to reproduce as the user
- report back

**Comment by jordanh** [comment] 2021-12-28 19:46
AC:
  - Triage for 1 hour and fix, or create a new issue

EE: 1 hour

**Comment by tianrunhe** [comment] 2022-01-20 22:26
I took a look at the journey for this user and I saw this weird event we published to Amplitude:  
 

![](https://user-images.githubusercontent.com/1879975/150427930-8ed62ca8-3321-4860-b1eb-582893326c28.png)

The user started a 3-minute timer on 18:55:46 so theoretically the `newScheduledEndTime` should be 18:58:46 but as you can see here, we reported that the `newScheduledTime` as 18:56:38, which is 2 minutes and 8 seconds off.

Now enter the interesting part: I took a look at a couple of other timer related events, they are ALL exactly 2 minute and 8 second off!  
From code [here](https://github.com/ParabolInc/parabol/blob/18fa6c14ca882daa97ea621fc855f5247afd474c/src/universal/components/StageTimerModalTimeLimit.tsx#L49) we can see that we are using `Date.now()` to get the current time from the client. So I guess what happened is that the client's time is not synced?

However, even with a wrong time set locally, I cannot reproduce what the user described (not able to set or add a timer).

We reached out to the customer but did not get any response. We are still getting timer related events from this user consistently and I took a look of the recent ones and they all look good (i.e., no more time mismatch).

I'm closing this issue now as it's not reproducible and it seems working for the user right now. Feel free to re-open if we hear more customers experiencing this issue or similar.

**Comment by drewhousman1010** [comment] 2022-01-20 22:27
Interesting! Thanks @tianrunhe

**Closed** 2022-01-20 22:28 UTC
Labels: bug, p2

**Comment by drewhousman1010** [comment] 2022-01-21 22:36
@tianrunhe the original user replied to my email asking if this was still a problem. This was the response:

> Yes, the timer has been working for me. It was an odd case of PEBKAC; not to imply that's unusual for me, but the circumstances thereof.
> 
> I had, for reasons that are completely forgotten to me, turned off NTP on my local machine.  Enough time creep had taken effect to throw my system off roughly two minutes, which was the first increment of time I was able to add to any timers in your system.
> 
> Turning NTP back on resolved the issue.  So sorry for any inconvenience I may have caused in not ensuring it was my system first.
>
